### ISSUE TITLE
The api key contains underscore could not save 

### ISSUE THREAD

**Issue by gregxing** [ucla/moodle-mod_zoom#1]
mod_zoom | api_key (Zoom API Key) when i input 6AMbJy61Ryq_xQowwKFBRQ and click save, it failed with the error message Invalid Value. When I change the _ to other character, it could save. Please check.

**Comment by rlorenzo** [comment]
@gregxing Going to have someone work on this, but in the meanwhile, I hope that isn't your real API key. If so, please be sure to regenerate it.
