### ISSUE TITLE
Zoom Organization URL

### ISSUE THREAD

**Issue by fabiocarreto** [ucla/moodle-mod_zoom#100]
Hi,

I'm, using your module for zoom integration.
I'm getting an error while creating the Zoom Meeting activity.
Does Zoom URL is required right?

That means I should have a branding account (with more then 10 hosts) so I can have access to that unique url?

Regards

**Comment by jrchamp** [comment]
This is probably the same as #86 .

You may want to try using the default: http://zoom.us/

**Comment by rlorenzo** [comment]
I am not sure this plugin works without a edu/business account. Never tried it and the complains that people saying this does not work is usually because of that. You need to be able to create a JWT app.
