### ISSUE TITLE
Feature Request: Optional Recording Link

### ISSUE THREAD

**Issue by nstefanski** [ucla/moodle-mod_zoom#101]
What I'm thinking is an extra field where the instructor could manually add a link to the meeting recording, either in Zoom's own cloud platform or a separate repository (we use YouTube). After the scheduled meeting, a student could follow the link to get a grade / complete the activity.

This is somewhat related to #46, with the downside of not being automatic, but the upside that institutions without cloud recording could still make use of it.

This is a feature I might be able to code myself, if so I'm curious if this is something you'd add to the plugin?

**Comment by jrchamp** [comment]
It would be ideal if you can allow multiple. Then #46 would be able to populate entries to the same place.

**Comment by nstefanski** [comment]
That's a good idea @jrchamp . It would probably be simple enough to store a list of comma-separated urls in the database. For completion marking, it would probably only be feasible to mark if ONE of the urls was viewed.

**Comment by jrchamp** [comment]
A delimited list would be the simplest. You won't be able to store any metadata though unless you either create a zoom_recordings table or use structured content like JSON.

**Comment by rlorenzo** [comment]
Closing as this duplicates https://github.com/ucla/moodle-mod_zoom/issues/46
