### ISSUE TITLE
Feature Request: Allow to password protect webinars

### ISSUE THREAD

**Issue by subedap** [ucla/moodle-mod_zoom#107]
Currently the plugin allows to use a password when creating a meeting. Also if the zoom account allow to embed the password in the link, the password is included in the plugin link in Moodle.

But the plugin currently not support to put a password to a webinar which could be a security problem.

The Zoom API currently support it: https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinarcreate

Thanks!

**Comment by rlorenzo** [comment]
Fixed in https://github.com/ucla/moodle-mod_zoom/commit/c71cc0862ca072d72b1a916fc1353572d9ccd572
