### ISSUE TITLE
Feature Request: Recycle License on Click Join event

### ISSUE THREAD

**Issue by mrvinceo** [ucla/moodle-mod_zoom#109]
The recycle license function is incredibly useful, but on occasions can result in a host with an upcoming event having their license removed prior to their meeting start time. Could the license recycling function also be applied to the join_meeting_button_clicked event, for just the meeting host? This way, as long as all hosts are funnelled through the created event, there's no risk of them not having a license. Alternatively, could the license recycling process also take into account whether the least active licensed user has an upcoming event?

Many thanks for an excellent plugin!

**Comment by mrvinceo** [comment]
Just to add to this, we've moved the recycle license behaviour from the create_meeting class into a class of its own 
 - provide_license() - allowing us to call this from both the create_meeting class and towards the end of loadmeeting.php to ensure licenses are recycled at the point of need as well as when the meeting is scheduled in (https://github.com/ucla/moodle-mod_zoom/compare/master...mrvinceo:oca_licenseRecycleOnJoin_mod). 

Seems to be working well in keeping everyone licensed so far, although I appreciate there will be a performance hit in doing it this way.

**Comment by jrchamp** [comment]
Very interesting idea. I added a suggestion to the commit and it looks like there may be some stray spacing changes, but I would guess it'll be an improvement for people who rely on automatic license reallocation.

It may be worth noting that if Join Before Host is enabled, there's could be a bit of a race between the Meeting Host and anyone else who joins. I would guess that - once the meeting has started - changing the licensed status doesn't have an effect on the live meeting.

Side idea: I wonder if it's worthwhile to show the license status of the meeting host to the users with `addinstance`. Perhaps when prompted? This may primarily be useful if recycling is active, but might be helpful to others as well.

**Comment by rlorenzo** [comment]
@mrvinceo Please make sure to submit a pull request. We would want the option to have this disabled for us, but might be useful or other.s

**Comment by mrvinceo** [comment]
Thanks @jrchamp & @rlorenzo - have made some changes as per your suggestions and will submit pull request shortly.

**Comment by rlorenzo** [comment]
Implemented in https://github.com/ucla/moodle-mod_zoom/pull/119
