### ISSUE TITLE
Code violations

### ISSUE THREAD

**Issue by ernperez** [ucla/moodle-mod_zoom#11]
In trying to get this plugin added to our Moodle instance, we had Moodlerooms do a code review. In that review they found some major violations, as defined in the attached summary. 

[ZoomPluginCodeReviewSummaryforCSU-Northridge_07282016.pdf](https://github.com/ucla/moodle-mod_zoom/files/391299/ZoomPluginCodeReviewSummaryforCSU-Northridge_07282016.pdf)

Can you all look at the issues and let me know if you are able to fix them?

thanks,

ernie perez

**Comment by rlorenzo** [comment]
@ernperez Reading the report I wouldn't' say they are "major" violations. They are both marked as minor issues. But we will create two issues for the "Semi-Deprecated Functions" and "Language files should have utf-8 encoding".

We will also take a look into the performance of zoom_update_records.

**Comment by ernperez** [comment]
Thank you much.

Ern


--
Ernie Perez
Director, Instructional Technologies
California State University, Northridge
18111 Nordhoff Street<x-apple-data-detectors://1/1> - OV 34
Northridge, CA 91330-8223<x-apple-data-detectors://2/0>
Email: ernie.perez@csun.edu<mailto:ernie.perez@csun.edu>
Office: 818-677-5144<tel:818-677-5144>

On Jul 29, 2016, at 4:24 PM, Rex Lorenzo <notifications@github.com<mailto:notifications@github.com>> wrote:


@ernperez<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ernperez&d=CwMCaQ&c=Oo8bPJf7k7r_cPTz1JF7vEiFxvFRfQtp-j14fFwh71U&r=bh1acgZY7PstgzQg1BMDBxVUvJ55joxcOPtOkJ46q4o&m=B2-b9PNHeVjsqT58GgNAznM0FAc-Clp4R5ScDn4k4a4&s=DAd_X4g7jU3Sk1N6XipnvG3CT9iRadj6HOQ2oL7NxM0&e=> Reading the report I wouldn't' say they are "major" violations. They are both marked as minor issues. But we will create two issues for the "Semi-Deprecated Functions" and "Language files should have utf-8 encoding".

We will also take a look into the performance of zoom_update_records.

-

**Comment by rlorenzo** [comment]
@ernperez The issues brought up by the review have been addressed in our v1.6 release.

**Comment by ernperez** [comment]
Thank you!


ern


--
Ernie Perez
Director, Instructional Technologies
California State University, Northridge
18111 Nordhoff Street - OV 34
Northridge, CA 91330-8223
Email: ernie.perez@csun.edu
Office: 818-677-5144
Video call: https://csun.zoom.us/my/ernperez


________________________________
