### ISSUE TITLE
Support Schedule For

### ISSUE THREAD

**Issue by mhughes2k** [ucla/moodle-mod_zoom#111]
It would be good if the schedule for parameter could be supported.

This is already a paramete (schedule_for) on the Meeting Create API https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate so in theory should just be a case of adding a text field that adds this data to the request.

This would really help for administrative staff that are setting up the activities on behalf of the teaching staff.

(I'll see if I can do a pull request for this, but no guarantees!)

**Comment by mhughes2k** [comment]
#112 Pull request to add parameter to form and to send to Zoom.

**Comment by mhughes2k** [comment]
I've also noted (not sure it it's always been there) the Assistants API (https://marketplace.zoom.us/docs/api-reference/zoom-api/users/userassistantcreate).

Given you can add users into a role on a user context, I wonder if you could do something with this that checks for any users assigned to a role with a "schedule_for" capability in a user-context. This would indicate that the the user assigned to that role is a (Zoom) assistant for them.

This would then allow assistant delegation to be done entirely within Moodle.

**Comment by jrchamp** [comment]
I'd be very hesitant to create assistants from Moodle. It would mean that someone like a TA would be able to see *all* of the instructor's Zoom meetings through the Zoom web interface, not just the ones for this course.

**Comment by mhughes2k** [comment]
If it's a user-context role assignment (rather than a course-context) given to a TA user on the Instructor user, that's equivalent to the current Zoom delegation.

**Comment by jrchamp** [comment]
That's still inside of Moodle. Adding an "assistant" to Zoom would give the user access to *all* of their Zoom meetings including employee 1-on-1, recruitment and retention meetings, and private family gatherings.

**Comment by mhughes2k** [comment]
Yes, it is still inside Moodle, but the feature in Zoom also has the same effect, all that's changed is the system that has applied that configuration.

Its mostly just a thought to raise, and I'm sure different institutions would have different practices. A lot of our requests at the minute are around admin staff being able to schedule Zoom meetings for the staff lecturing a particular class. We know who the admins in the class are and we know who the lecturers are in the class. 

So in order to use this the Zoom schedule for facility (and this *is* a separate concern from actually having the facility available in the plugin) we're either going to have to get all of the Lecturers to go into Zoom and authorise all of the administrators of all of their classes to be able to schedule them, or potentially look at automating that.

Either way the issue that you raise relating to the "private" meetings that aren't part of a class is still an issue, but one that is either accepted or you can't allow delegation of the scheduling of meetings anyway.

**Comment by mhughes2k** [comment]
If I create (in Zoom) a scheduled meeting for another colleague, I continue to see it, even though it's "theirs".

So I don't see how you avoid the visiblity issue without Zoom itself having a mechanism that allows the "actual" user to designate a meeting as not available to their schedulers to access / change, or provide a way to take a meeting that has been scheduled for them and prevent the original scheduler from ever seeing it again and it being a much more "hard" transfer of ownership of the meeting. This is of course then causes issues if that meeting needs to be transfered to (yet) another person.

**Comment by jrchamp** [comment]
Agreed, I understand what you mean. My point was more that I was scared of Moodle doing it automatically. If users opt-in to it (or the administration requires it), then I'm okay with it, because they know it's happening.

**Comment by rlorenzo** [comment]
Implemented in https://github.com/ucla/moodle-mod_zoom/commit/220db34b7002910daee57f356e5358b34427eecb

**Comment by mhughes2k** [comment]
Woo!! thank you very much guys! Look forward for this being in the release
