### ISSUE TITLE
Run meetings in the browser! 

### ISSUE THREAD

**Issue by naamaan** [ucla/moodle-mod_zoom#114]
Hi,
I need to run the zoom meetings within the browser not through the app.
I tried to launch the session from the browser after clicking “Start Meeting“ button, but it keeps sending me back to the zoom sign in page!
Is there any way to do that?
Thanks in advanced.

**Comment by jrchamp** [comment]
Nope, the Zoom Web Client requires login as of April: https://devforum.zoom.us/t/zoom-asking-for-sign-in-always/11347/2
