### ISSUE TITLE
Mood_zoom Connection failed: HTTP Status 403

### ISSUE THREAD

**Issue by KamalSaeidi** [ucla/moodle-mod_zoom#116]
I have installed Moodle zoom meeting and entered zoom API key, Api secret and home page URL in this plugin settings but encountered following message:
Connection status: Connection failed: HTTP Status 403

**Comment by rlorenzo** [comment]
That is a common problem mentioned here: https://moodle.org/plugins/mod_zoom

Things to check:
* Make sure JWT app is properly setup
* Make sure system time is up to date
* Make sure you have a business or educational Zoom account
