### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by mhughes2k** [ucla/moodle-mod_zoom#121]
Am i right in thinking that this plugin doesn't actually show the meeting password to participants?

![image](https://user-images.githubusercontent.com/694841/90642799-c0d66000-e22a-11ea-9cb0-785eb33b663c.png)

**Comment by jrchamp** [comment]
I think you are correct. It's also worth noting that they rebranded it to "Passcode" because it's not a username/password.

**Comment by mhughes2k** [comment]
Also, with the embed pass(word|code) in link option being a settable at various levels (so for instance in our case it's turned off by default), shouldn't the plugin:
* display it in the UI, rather than having to get the staff to copy & paste it in to the description
* allow the host to set whether or not it is embeded (based on if its allowed) so that if it is not locked they can select it themselves.

**Comment by jrchamp** [comment]
Yes, I do think that it would be good to display the passcode in the UI.

I don't think the Moodle plugin has the ability to embed if it's not already embedded by Zoom because the format is different. Maybe it's something simple like base64, but I haven't looked into the format.

Soap box: Embedding the password is what I recommend, because there's not security benefit to not embedding and it just makes the user experience worse.

**Comment by mhughes2k** [comment]
> Soap box: Embedding the passcode is what I recommend, because there's no security benefit to not embedding and it just makes the user experience worse.

I do agree with this too, but you know...decisions. 

Hopefully with people being more aware of the other settings then it's less of any avenue for all the bad things that were happening because the password was the *only* measure.

**Comment by mhughes2k** [comment]
@rlorenzo i don't see a problem with obscuring the direct link, the problem is not showing the passcode and having to manually communicate it. 

For instance if the feature is disabled, you still get the link and passcode on the same email just as separate pieces of text. 

With a large number of meetings being set up and staff needing to also remember to copy the passcode into the description for the students, it would just be a step that could be eliminated.

**Comment by ndunand** [comment]
I second @jrchamp and @mhughes2k on not displaying the password to students, which really is a problem for us and forces us to manually communicate passwords for each Zoom activity.

@rlorenzo could there be a site-wide option that would allow a display logic like this:

```
if ($haspassword && ($userishost || $showpasswordtostudents)) { 
     $table->data[] = array($strpassword, $zoom->password); 
 }
```

**Comment by mhughes2k** [comment]
Pull request for this #139

**Comment by rlorenzo** [comment]
Merged https://github.com/ucla/moodle-mod_zoom/pull/139
