### ISSUE TITLE
Connection status: Connection failed: Invalid access token

### ISSUE THREAD

**Issue by JeremyNichvalodoff** [ucla/moodle-mod_zoom#122]
Created a JWT app for the Key and Token entered the data and saved plugin in Moodle and get the error: Connection status: Connection failed: Invalid access token.

Have tried copy and pasting, copy and pasting from plain text editor to remove any hidden characters, typed out the info. 
Have tried multiple JWT apps to get Key and Token.

**Comment by rlorenzo** [comment]
@JeremyNichvalodoff Make sure the clock on your system running Moodle is synced with a time server. Errors can happen if there is a time difference.

Else, try reactivating your JWT app. Other problems please see this: https://devforum.zoom.us/t/jwt-app-is-not-working-on-multiple-zoom-accounts/11672/20

You might need to contact Zoom Dev support.
