### ISSUE TITLE
Overriding of the $url parameter causing issue in recursive rate limiting calls

### ISSUE THREAD

**Issue by kbowlerarden** [ucla/moodle-mod_zoom#128]
https://github.com/ucla/moodle-mod_zoom/blob/abe89c5dfc1bf8caedd2c29e3ad681230f14a0fb/classes/webservice.php#L170 

We were seeing an issue where $url was being passed into rate limited calls after the contents had been appended to themselves.

I have fixed by declaring a new local variable inside the function and passing that to the curl call. Will attach pull request.

**Comment by kbowlerarden** [comment]
Pull request: #129

**Comment by kubilayagi** [comment]
resolved by https://github.com/ucla/moodle-mod_zoom/tree/feature/CCLE-9507-zoom-fix-url-append
