### ISSUE TITLE
Support Zoom Web SDK

### ISSUE THREAD

**Issue by naamaan** [ucla/moodle-mod_zoom#130]
Hi,
Is there any intention to support the Zoom Web SDK in the future?
Best regards,

**Comment by rlorenzo** [comment]
@naamaan I read https://marketplace.zoom.us/docs/sdk/native-sdks/web and found no reason why to use it. If you can highlight some reasons, let us know.

**Comment by naamaan** [comment]
Sorry for this late answer,
The reason is our client wants to open the meetings in the Moodle page, and then to apply some identity customization to the page containing the meeting, for example: to but a logo image as a layer on the meeting window during the meeting.

At the end, I could do that by my self, I embedded the Web SDK in the php page and it worked, but not sure if it's the best integration. I could share my solution with you if you like.

Best regards,

**Comment by mwithheld** [comment]
@naamaan Could you post your Web SDK code (PHP and JS)?

**Comment by mwithheld** [comment]
@rlorenzo I am looking to use the Web API to embed the Zoom UI within the Moodle page.
