### ISSUE TITLE
Check for pending users

### ISSUE THREAD

**Issue by kbowlerarden** [ucla/moodle-mod_zoom#131]
Hello again,

We are seeing issues with the Zoom API returning a 400 error when we try and create sessions a pending user.  This is obviously the correct behaviour, but the error message that is returned for the plugin says "Zoom received a bad request: {$a}".

Would it be possible to perform some extra error checking around pending users? 

Suggestions:

1. Throw an exception if the status is "pending" from the initial get_user call
2. Check for errors in the response when the return HTTP code is 400: {"code":1000,"message":"You can not access settings of users that are still in pending state."}

![IMG_0666](https://user-images.githubusercontent.com/47315427/92745219-127d9080-f37a-11ea-9bc7-bf0977db2fcb.JPG)

Let me know if you want me to develop this and submit a pull request.

Finally I just want to say thanks for a great plugin, we are using a lot right now and it has saved us a bunch of time already!

**Comment by rlorenzo** [comment]
@kbowlerarden Yes, please let us know if you can have a patch to give a better error message for pending users. Never ran into this problem so good to know you can replicate the error to be able to test your patch.

**Comment by rlorenzo** [comment]
@kbowlerarden Is this still an issue? I tried creating a meeting as a pending user and didn't run into the error above. I get an error that says "Unable to find your account on Zoom". The Zoom API returns a 404 error code, not 400 for me.
