### ISSUE TITLE
[Feature]Translation to uk, ru and pl

### ISSUE THREAD

**Issue by mkikets99** [ucla/moodle-mod_zoom#132]
***\*\*\*All dates are in "yyyy/mm/dd" format\*\*\****
***\*\*\*It`s a feature request\*\*\****

Hi. I can control translation to those 3 languages.

Languages in progress of translating (manually):

- [x] uk (Ukrainian) (**done** at 2020/09/11)
- [x] ru (Russian) (**done** at 2020/09/12)
- [x] pl (Polish) (**done** at 2020/09/12)

If you are interested of implementing those languages to _mod please inform me.

**Comment by rlorenzo** [comment]
@mkikets99 Thanks for the contribution. Will you be uploading a translation file or making a pull request when done?

**Comment by mkikets99** [comment]
I can make both. Maybe pull request will be better, because i am already editing it on clone.

**Comment by mkikets99** [comment]
@rlorenzo I completed it. All three are ready to publish.

**Comment by rlorenzo** [comment]
@mkikets99 I don't see a link to the translations or a pull request. Can you please open a pull request so I can merge it in?

**Comment by mkikets99** [comment]
Well, the problem is that i don't have write permission to even create branch...
I don't even know why...

**Comment by rlorenzo** [comment]
@mkikets99  You needs to fork this repo and then you can push to your copy. I can then pull the code from your fork to this repo.

**Comment by mkikets99** [comment]
@rlorenzo Here we go, pull request is ready.
It`s actually my first time when I created pull request from fork, so don`t put blame on me.
