### ISSUE TITLE
PHP catchable fatal error

### ISSUE THREAD

**Issue by valeriy67** [ucla/moodle-mod_zoom#138]
Hello!
The new version of the plugin gives an error
Coding error detected, it must be fixed by a programmer: PHP catchable fatal error
Moodle 3.9.2, php 7.2

The previous version (3.2) worked normally.

Thank you!

**Comment by rlorenzo** [comment]
@valeriy67 Is this related to https://moodle.org/mod/forum/discuss.php?d=410650? If you change the passcode with uppercase/lowercase and @ sign does it work?
