### ISSUE TITLE
Alternative hosts possible bug?

### ISSUE THREAD

**Issue by roeycohen** [ucla/moodle-mod_zoom#140]
Hi (@rlorenzo),

$userishost is checked differently in two different places:

On:
https://github.com/ucla/moodle-mod_zoom/blob/129bb264e8c16d357516dc62307ae0f2b3ce97a7/view.php#L61

But on:
https://github.com/ucla/moodle-mod_zoom/blob/129bb264e8c16d357516dc62307ae0f2b3ce97a7/loadmeeting.php#L42

Is it possible that on the dialog, an alternative host will see "start meeting" but on launching the meeting he will be treated as a student?

**Comment by rlorenzo** [comment]
@roeycohen The actual determination if a user us a host for a Zoom meeting happens on the Zoom client. So if they are an alternative host, Zoom should still know that and give them appropriate access.

However, it would affect if you use the recycleonjoin setting at https://github.com/ucla/moodle-mod_zoom/blob/129bb264e8c16d357516dc62307ae0f2b3ce97a7/loadmeeting.php#L81

Would you be able to provide a patch to make the determination of userishost as a function instead so the logic can be consolidated into a single place?

**Comment by roeycohen** [comment]
Hi @rlorenzo, 

Thanks for answering!

I won't be able to help you here much, I'm not really a moodle user, just exploring Zoom integration for another project :)

10x!

**Comment by rlorenzo** [comment]
Actually, we tried using the same logic to, but only the true host of the meeting should get the start_url link. Otherwise alternative hosts were joining in as the host and you end up having multiple people in the meeting with the same name as the host.
