### ISSUE TITLE
Schedule for feature doesn't list non-editing tutors.

### ISSUE THREAD

**Issue by FraserConnolly** [ucla/moodle-mod_zoom#142]
Hi, The 'schedule for' drop down box currently filters such that only those who are able to create a Zoom meeting element on a course are listed in the drop down. I'd argue this is unhelpful as we, University of Strathclyde, regularly want to have meetings where one of our non-editing tutors should be the host. 

I'm not a php expert but the change would be somewhere around line 67 of mod_form.php.

https://github.com/ucla/moodle-mod_zoom/blob/f0301cc47c6de69271d27ff6e8ebb0acf7adf592/mod_form.php#L67

Cheers

Fraser

**Comment by jrchamp** [comment]
Indeed, right now it limits it to people who can create Zoom activities.
https://github.com/ucla/moodle-mod_zoom/blob/f0301cc47c6de69271d27ff6e8ebb0acf7adf592/mod_form.php#L77

It probably still makes sense to limit the list to users who are part of the course. Perhaps `mod/zoom:view`?

**Comment by FraserConnolly** [comment]
I think that works for me. I'm just a little worried about how the view capability is influenced by Group restrictions. 

I suspect I'd need to test it to be sure but as I'm not on that development team I don't think that I would be able to do that.

Cheers

F

> Indeed, right now it limits it to people who can create Zoom activities.
> https://github.com/ucla/moodle-mod_zoom/blob/f0301cc47c6de69271d27ff6e8ebb0acf7adf592/mod_form.php#L77
> 
> It probably still makes sense to limit the list to users who are part of the course. Perhaps `mod/zoom:view`?

**Comment by rlorenzo** [comment]
Closing since 'mod/zoom:addinstance' is on purpose. The user you are scheduling for must also be able to edit the meeting, else you can create meetings for users and they cannot control them.
