### ISSUE TITLE
Button link not updated when setting/changing passcode for zoom meeting

### ISSUE THREAD

**Issue by cdipe** [ucla/moodle-mod_zoom#145]
**v3.1 (2020061200)**
When an already created meeting without a password is edited and provided with a passcode, the link in the Join Meeting button is not updated with a passcode.

**v3.3 (2020091400)**
The plugin has forced passcode, but when the meeting is edited and the passcode is changed, the link in the Join Meeting button still have the old passcode.

**Comment by rlorenzo** [comment]
@cdipe Make sure the mod_zoom\task\ update_meetings task is running. That is when join links are updated.

**Comment by cdipe** [comment]
Thank you, @rlorenzo
