### ISSUE TITLE
Disable chime option

### ISSUE THREAD

**Issue by aspark21** [ucla/moodle-mod_zoom#146]
"Sound notification when someone joins or leaves" is enabled by default with no setting in Moodle to manage this.
If the session was created in zoom.us directly thatsetting is present.

Lecturers are finding this distracting when students leave & joining throughout a lecture. 

The same applies to chat messages but there doesn't seem to be a setting for that on the zoom end.

**Comment by jrchamp** [comment]
This plugin doesn't set that value, so it's likely defaulting to the user's profile setting: https://zoom.us/profile/setting

**Comment by rlorenzo** [comment]
@aspark21 I don't see that as an option when creating meetings. See https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate

So it must be a per-user setting as @jrchamp suggests above. Closing.
