### ISSUE TITLE
How do "Redefine licenses" and "Recycle license upon join" works?

### ISSUE THREAD

**Issue by KeremKoksal** [ucla/moodle-mod_zoom#147]
"If the number of your licenses exceeds those required, then when you create each new activity by the user, it will be assigned a PRO license by lowering the status of another user."

How does it choose the user to lower? Is it totally randomly or does it check if the user is in a meeting? What happens if all the license holders are in a meeting?

**Comment by mrvinceo** [comment]
Hi KeremKosal,
It's based on the least active user, which is based on last login time; it strips a license away from that user and allocates it to the new host. As long as you have more than a handful of licenses to allocate, it's unlikely that a user who is currently hosting a meeting would be deemed 'least active', but it's a limitation to bear in mind when using the feature.

If all license holders are in a meeting, the least active of those (the last to join it, I'd guess) would have their license removed.

**Comment by KeremKoksal** [comment]
Thanks for the response mrvinveco.
