### ISSUE TITLE
Connection failed: Access token is expired

### ISSUE THREAD

**Issue by j2wong** [ucla/moodle-mod_zoom#150]
Hi

I encountered the captioned message when I input the API Key and secret (which are generated by Zoom JWT) into the Zoom meeting settings at Moodle.  For the zoom, my account is educational type and granted as admin role.  My Moodle version is 3.9.

I tried to regenerate the API and secret and activated the JWT app, but still in vain.

Any step or configuration I missed or incorrected?  How to find out the issue?  Please advise.

Thanks,
James

**Comment by fabiankoeninger** [comment]
I have the same problem. Is there any solution for this issue?

**Comment by mikhail-cct** [comment]
Go to [](https://marketplace.zoom.us/develop/create) and press **View Here**, then click **View JWT Token** and you will see the next heading appearing, which is **Expiration Time**. Change the values there, as desired.

**Comment by j2wong** [comment]
I set the expiry date to 00:00 31 Dec, 2020, but the error message is still here when I clicked the "Save Changes" in the Zoom Meeting setting.  If the JWT Token is valid, how to know that Moodle is reached the corresponding API?  It is just input the Zoom's API Key and secret in the settings only.

**Comment by mikhail-cct** [comment]
If you would like to see whether you can actually reach Zoom API, please use the [following tutorial](https://www.youtube.com/watch?v=eMzbAWFjz6M). Download Postman, Import the following [Collection](https://marketplace.zoom.us/docs/api-reference/zoom-api/Zoom%20API.oas2.json), put in your JWT credentials and test any API calls. It will give you an idea whether the problem is on the Zoom's end or in Moodle.

**Comment by j2wong** [comment]
Thanks for your information.  The JWT token is valid because I used it to pass the authentication to get the data from Zoom API when following the instruction in the tutorial.  Then, how to test the plugin has sent out the request to Zoom using the API Key and secret?

**Comment by j2wong** [comment]
I found out the problem.  The Moodle Server's time does not up-to-date.  After sync with time machine, the connection immediately works.

Thank you so much for the great support!
