### ISSUE TITLE
Moodle quick edits don't carry through to Zoom or Moodle calendar

### ISSUE THREAD

**Issue by hovez701** [ucla/moodle-mod_zoom#156]
Quick edits on Moodle don't carry through to Zoom, or to the Zoom meeting item in the Moodle calendar.

To reproduce:
	1. Create Zoom meeting in Moodle
	2. Navigate to Moodle course home page to see Zoom meeting activity link
	3. Turn on editing and click pencil icon to edit Zoom meeting name.
	4. Check Zoom web or Desktop app. Meeting name is not updated.
	5. Check Moodle calendar. Meeting name is not updated.
	
Moodle Version: 3.7.8
Zoom plugin: v3.2 2020090400

Could you assist?

**Comment by jrchamp** [comment]
Since the inline edits do not touch the plugin code, we probably need to register an observer for the `\core\event\course_module_updated` event, similar to other code in core: https://github.com/moodle/moodle/blob/6153be6850869cdc3a6ae925dcf6e688ac481333/mod/glossary/db/events.php#L27-L32
