### ISSUE TITLE
Zoom link not updated when adding a password

### ISSUE THREAD

**Issue by f0k** [ucla/moodle-mod_zoom#158]
The Zoom plugin was recently updated to require a password for meetings. We had a Zoom meeting on a Moodle page that had been created before that change. When we updated some setting for the Zoom meeting on Moodle, we were required to set a password for it. After saving, the Zoom meeting was changed to require a password, but the "Join meeting" link/button on Moodle was still the original one, without a password, so students could not join the meeting.

Hope this helps to reproduce the problem -- I cannot reproduce it in our production environment because I cannot create a password-less Zoom meeting on Moodle any longer.

Thanks for developing and maintaining this plugin! :+1:

**Comment by ckong11** [comment]
You may want to have the user check their Zoom.us settings as well. There is a setting titled "Embed passcode in invite link for one-click join." If this is not toggled on, the passcode will not be added anytime a user shares their Zoom meeting link.

**Comment by rlorenzo** [comment]
@f0k Make sure that the mod_zoom\task\update_meetings task has run. That is what updates the meeting links. By default, it runs every 30 minutes, but if there's an error when running it, it might not update all meetings.
