### ISSUE TITLE
Add phone in details to Meeting page

### ISSUE THREAD

**Issue by emmarichardson** [ucla/moodle-mod_zoom#159]
Some of our Zoom attendees need to be able to join from a phone and the dial in instructions are not on the zoom page - could we please get that added please??

**Comment by rlorenzo** [comment]
@emmarichardson We can get the invitation text, like:

> Join Zoom Meeting
> https://ucla.zoom.us/j/MEETINGID?pwd=PASSCODE
> 
> Meeting ID: MEETINGID
> Passcode: PASSCODE
> One tap mobile
> +16692192599,,MEETINGID#,,,,,,0#,,PASSCODE# US (San Jose)
> +12133388477,,MEETINGID#,,,,,,0#,,PASSCODE# US (Los Angeles)
> 
> Dial by your location
>         +1 669 219 2599 US (San Jose)
>         +1 213 338 8477 US (Los Angeles)
>         +1 346 248 7799 US (Houston)
>         +1 602 753 0140 US (Phoenix)
>         +1 720 928 9299 US (Denver)
>         +1 971 247 1195 US (Portland)
>         +1 253 215 8782 US (Tacoma)
>         +1 786 635 1003 US (Miami)
>         +1 301 715 8592 US (Washington D.C)
>         +1 312 626 6799 US (Chicago)
>         +1 470 250 9358 US (Atlanta)
>         +1 646 558 8656 US (New York)
>         +1 651 372 8299 US (St. Paul)
> Meeting ID: MEETINGID
> Passcode: PASSCODE
> Find your local number: https://ucla.zoom.us/u/ahGxyLEIa
> 
> Join by SIP
> MEETINGID@zoomcrc.com
> 
> Join by H.323
> 162.255.37.11 (US West)
> 162.255.36.11 (US East)
> 115.114.131.7 (India Mumbai)
> 115.114.115.7 (India Hyderabad)
> 213.19.144.110 (Amsterdam Netherlands)
> 213.244.140.110 (Germany)
> 103.122.166.55 (Australia)
> 149.137.40.110 (Singapore)
> 64.211.144.160 (Brazil)
> 69.174.57.160 (Canada)
> 207.226.132.110 (Japan)
> Meeting ID: MEETINGID
> Passcode: PASSCODE

See https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetinginvitation

I don't see an easier way to get the phone info from the Zoom API.

**Comment by emmarichardson** [comment]
That seems excessive for the main page...maybe we could link to a pop up with that information?

**Comment by rlorenzo** [comment]
Done in https://github.com/ucla/moodle-mod_zoom/pull/170
