### ISSUE TITLE
FR or Bug: Passcode field rules and info doesn't reflect passcode policy for Zoom server

### ISSUE THREAD

**Issue by danowar2k** [ucla/moodle-mod_zoom#160]
This issue is probably the base of other issues here, e.g. #138 .

At the moment the passcode field in the activity form only respects hardcoded passcode rules:
- minlength 1 char
- maxlength 10 chars
- allowed chars: [a-zA-Z0-9@_*-] (the current regex)

See https://github.com/ucla/moodle-mod_zoom/blob/366bffafb3b8faf41bf25ac6951972e0d0655b53/mod_form.php#L202-L209.

I don't know if the Zoom API provides a way to query the passcode policy...

* If there is a way to query it, one could use the response to create the passcode field rules.
* If there is no API for this, the passcode policy should probably be extracted to settings for the plugin (minlength, maxlength, allowed chars). Possibly this needs to be done for multiple Zoom servers? I don't know how many zoom servers can be used simultaneously with this plugin...

**Comment by rlorenzo** [comment]
We can get advanced passcode requirements by calling:

- https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usersettings

  - meeting_password_requirement

- https://marketplace.zoom.us/docs/api-reference/zoom-api/accounts/accountsettings

  - password_requirement

This plugin can only support one Zoom server. This is on our backlog, but no work has progressed on it. Discussion on Moodle forum at: https://moodle.org/mod/forum/discuss.php?d=410650

**Comment by danowar2k** [comment]
So I see you already have a wrapper for Zoom API calls here in classes/webservice.php. Am I blind or is there nowhere _make_call is used yet?

**Comment by danowar2k** [comment]
So, the next question to me is what's the difference between calling the account and the user webservice? Both can respond with password criteria. When should one use one over the other? Or should one always use both and merge the results in some way?

**Comment by rlorenzo** [comment]
@danowar2k Okay, looking at the API again, I believe https://marketplace.zoom.us/docs/api-reference/zoom-api/accounts/accountsettings and the password_requirement call is the password requirement related to Zoom user accounts. I see they match up to the Zoom end of ADMIN > Advanced > Security> Authentication.

So that is not related to Meeting Passcodes. 

The section in the admin where Meeting Passcodes are set is at ADMIN > Account Management > Account Settings > Passcode Requirements. At our institution, we do not have any of these set, so it would be difficult for us to really test the API call is getting the right data.

**Comment by jrchamp** [comment]
https://marketplace.zoom.us/docs/api-reference/zoom-api/accounts/accountsettings with `option=meeting_security` seems like the right one.

Here's the response format:
![image](https://user-images.githubusercontent.com/625298/99005880-9802f580-250f-11eb-9175-532c62f866f8.png)

**Comment by rlorenzo** [comment]
@danowar2k We have a patch that can fix this. See https://github.com/ucla/moodle-mod_zoom/pull/177

We are unable to change the settings on our Zoom instance to enable different passcode requirements, even for the user level, would you be able to help verify that our patch works?

**Comment by danowar2k** [comment]
Don't know, I'll ask if we can check it...
