### ISSUE TITLE
Bug: Calendar icon in non-Boost theme not getting loaded

### ISSUE THREAD

**Issue by danowar2k** [ucla/moodle-mod_zoom#161]
The calendar icon on view.php isn't getting loaded in non-Boost themes, it seems. Maybe it's just non-Font-Awesome-using themes, I don't know.

Anyway, the reason seems to be that you explicitly want the i/calendar icon from the plugin mod_zoom, but the calendar icon is Moodle core.

https://github.com/ucla/moodle-mod_zoom/blob/366bffafb3b8faf41bf25ac6951972e0d0655b53/view.php#L157

Fix:

`$calendaricon = $OUTPUT->pix_icon('i/calendar', get_string('calendariconalt', 'mod_zoom'));`

Without the fix, the generated image url is something like:

> https://moodle.instance/theme/image.php/theme_name/mod_zoom/1605014640/i/calendar

Which of course leads nowhere.

**Comment by rlorenzo** [comment]
@danowar2k Looks like a simple fix, just leaving out 'mod_zoom' as the 3rd parameter? Would you be able to provide a pull request? I can approve it.

**Comment by danowar2k** [comment]
@rlorenzo I've added a PR since then, just so you know...

**Comment by rlorenzo** [comment]
@danowar2k Merged. Sorry, I don't get email notifications of new pull requests.
