### ISSUE TITLE
Wrong participants in sessions

### ISSUE THREAD

**Issue by ASNi62** [ucla/moodle-mod_zoom#168]
Hi,

We use ZOOM plugin in our Moodle (3.8+). 
When we check the participants in a ZOOM session via Moodle, we have noticed that some participants have been replaced by others. We don't know why, or how the plugin works.
For exemple : 
Victor De is enrolled in the Moodle course and has clicked on the Zoom activity (we can see it in the logs).
Victor Du isn't.
When checking the sessions afterwards :
- on zoom website, Victor De is a participant of the meeting (and it's OK !).
- in the zoom sessions available in the course on moodle, Victor De. can not be found, but we found another Victor.

The same for other participants whose names are quite alike (Valentine X. participated, but Valentin B. appears instead.
Or Jonathan D. participated but Jonathan V. appears instead in Moodle sessions).

Do you have any clue ?
We really don't understand...

Thanks !
A-Sophie

**Comment by rlorenzo** [comment]
@ASNi62 The get_meetings_report tries to match users on name if matching on email or if the user was not previously matched. See https://github.com/ucla/moodle-mod_zoom/blob/95e57dce8e76fa6aeaa1b82ae24e1e5efbcef742/classes/task/get_meeting_reports.php#L326

It matches users if they pass a 60% threshold. You can go in the database and rematch the students to the correct userid. Then for future runs on the report it will use those matches instead. Or change the SIMILARNAME_THRESHOLD value from 60 to something higher that works for your needs.
