### ISSUE TITLE
Configurable Appearance of Zoom activity in Moodle

### ISSUE THREAD

**Issue by erickuncoroeworks** [ucla/moodle-mod_zoom#17]
Your plugin is great! thank you.

Currently we host moodle for multiple clients, where they are getting used to the need of customising appearance in the activity.

I noticed we needed to have ability of setting up zoom activity to display in new page rather than the same page.

The similar idea sits under moodle's standard activity: URL as per screenshot attached.

Would it be possible for your plugin to have this extra configuration please?

Thanks.

![image](https://cloud.githubusercontent.com/assets/20413445/24847550/f08b8124-1e04-11e7-81ce-5924aee52129.png)

**Comment by rlorenzo** [comment]
@erickuncoroeworks This makes sense for the URL resource because the URL that the user is accessing can appear in a new window, embedded, etc.

However, for the Zoom plugin, the URL it launches will always load up into the Zoom client.

**Comment by nwp90** [comment]
For us, key reason for wanting to open in new window is to avoid accidentally losing Moodle, which does happen if it is opened in same window. I guess embedding it might be a cleaner way of achieving this.

Error messages also appear in the Zoom window...

**Comment by cdipe** [comment]
I agree, to open in new window is a much better solution.

**Comment by rlorenzo** [comment]
We are working on making the join meeting button open the url into a new window: https://github.com/ucla/moodle-mod_zoom/issues/26
