### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by mhughes2k** [ucla/moodle-mod_zoom#171]
Can we be expecting a new release some time soon? As it looks like there are a number of fixes etc that have been done, and the last 'formal' release was back in September now.

**Comment by rlorenzo** [comment]
@mhughes2k Yeah, I just need to fix a major problem with the get_meeting_reports task then will be making a release after that.

**Comment by rlorenzo** [comment]
Released new plugin at https://moodle.org/plugins/pluginversion.php?id=23076
