### ISSUE TITLE
PHP Fatal error:  Cannot declare class webservice_test

### ISSUE THREAD

**Issue by ewallah** [ucla/moodle-mod_zoom#172]
PHP Fatal error:  Cannot declare class webservice_test, because the name is already in use in mod/zoom/tests/webservice_test.php on line 505

Without namespacing, you shoud rename the class webservice_test to something like mod_zoom_webservice_test. Otherwise there are 2 webservice_test classes in Moodle, a situation PHP cannot handle.

**Comment by rlorenzo** [comment]
Fixed in master

**Comment by ewallah** [comment]
THX
