### ISSUE TITLE
how to hide meeting information

### ISSUE THREAD

**Issue by hakancigci** [ucla/moodle-mod_zoom#173]
My Issue is , when meeting load user can click on (i) and all meeting info is displayed , meeting number & password .

question is : how to hide meeting information , or allow users to join meetings through my moodle only .

**Comment by rlorenzo** [comment]
@hakancigci That was a feature request from our users to show phone info and that is only possible by showing the invite text. If you want to make it a config please create a pull request with code changes.

**Comment by hakancigci** [comment]
I hid it in the module. I saw that it is possible in sdk in Zoom application.

**Comment by rlorenzo** [comment]
Duplicate of https://github.com/ucla/moodle-mod_zoom/issues/193

Will be fixed there when that issue is completed
