### ISSUE TITLE
Empty report

### ISSUE THREAD

**Issue by Filaretis** [ucla/moodle-mod_zoom#174]
Hi there! 
Unfortunately, after updating mod_zoom to version 3.4, all meeting reports became empty (as if they were not carried out). Old conferences that were held on version 3.3 contain all past sessions.
_We have 2 moodle installations with 3.9.3 and 3.10 versions working with Edu zoom acc. Both have the same 'empty report' problem._

**Comment by rlorenzo** [comment]
@Filaretis When the get_meeting_reports.php task ran (try viewing the task logs under the task report in Site administration), did it say:

"Dropping previous records of X participants" where X is the number of participants?

It should only be processing meetings that are still on Zoom and should have records. Try manually running this CLI script:

php mod/zoom/cli/get_meeting_report.php --start=2020-11-18 to try to repopulate meetings from the past 30 days.

**Comment by Filaretis** [comment]
Detailes and participants DB zoom tables have been empty since updating to 3.4.

Output of get_meeting_reports.php task just like:
_Finding meetings between 2020-12-17 to 2020-12-18
Using Dashboard API
Found 30 meetings
Found 0 webinars
Processing 30 meetings
Processing meeting 9448593####|*****YgSRHWhD9vhjJz0fw== that occurred at 1608184301
Inserting zoom_meeting_details
Processing meeting 9882353####|*****GDATiG6a5oIaE8Npg== that occurred at 1608184389
Inserting zoom_meeting_details
........................................_

**Comment by almadog** [comment]
We have exactly the same problem as Filaretis.

**Comment by ASNi62** [comment]
Hello,
We have the same problem (after updating mod_zoom to version 3.4).
We did it to see the sessions and count unique users, but instead we don't have anything anymore :/ 
Thanks

**Comment by CarlosV-Inserver** [comment]
Hello,
I have the same problem with empty reports using plugin version 3.4 and moodle 3.9.3.
I have verified that reports do appear in the Zoom website, the problem is when I try to look at them in moodle because the plugin tables do not reflect anything new. I have verified that the scheduled task (/mod_zoom/task/get_meeting_reports) runs without any problem, but it doesn't insert the information into the database.

**Comment by rlorenzo** [comment]
The plugin now uses the Dashboard API to get meeting reports and that is available for business and higher plans, including educational accounts.

Maybe your accounts don't have access to the Dashboard API? To test, can you guys run this script?

`php mod/zoom/cli/get_meeting_report.php --courseid=<COURSEID> --start=2020-01-01`

Replacing <COURSEID> with a course you know had meetings. If that works then the Dashboard API is not working for some reason.

You can do a workaround right now by editing:

https://github.com/ucla/moodle-mod_zoom/blob/cd6549ee6097dd453584bc31acaacf307683d9e3/classes/task/get_meeting_reports.php#L144

`if (!empty($hostuuids)) {`

To

`if (true && !empty($hostuuids)) {`

Let me know if that works.. then I can put in a setting to choose the Dashboard API or older Reports API

**Comment by Filaretis** [comment]
> The plugin now uses the Dashboard API to get meeting reports and that is available for business and higher plans, including educational accounts.
> 
> Maybe your accounts don't have access to the Dashboard API? To test, can you guys run this script?
> 
> `php mod/zoom/cli/get_meeting_report.php --courseid=<COURSEID> --start=2020-01-01`
> 
> Replacing with a course you know had meetings. If that works then the Dashboard API is not working for some reason.
> 
> You can do a workaround right now by editing:
> 
> https://github.com/ucla/moodle-mod_zoom/blob/cd6549ee6097dd453584bc31acaacf307683d9e3/classes/task/get_meeting_reports.php#L144
> 
> `if (!empty($hostuuids)) {`
> 
> To
> 
> `if (true && !empty($hostuuids)) {`
> 
> Let me know if that works.. then I can put in a setting to choose the Dashboard API or older Reports API

Something was fetched
 _sudo -u www-data /usr/bin/php get_meeting_report.php --courseid=24 --start=2020-12-15
Finding meetings between 2020-12-15 to 2021-01-19T21:21:23Z
Using Reports API
Hostuuids passed
Processing 1 active host uuids
Getting meetings for host uuid NTCAcYwv****qK9fLfcLzQ
Found 2 meetings for user
Processing 2 meetings
Processing meeting 9318**87074|POGhGZTR**6u/Zte+pZFTw== that occurred at 1608875430
Updating zoom_meeting_details
Processing 10 participants
Dropping previous records of 10 participants
Working on Ник****унин (user_id: 167**240, uuid: cEmbJkhDR3***QcI_ORZgg)
Inserted record 32543
Working on Григо*****аев (user_id: 167**264, uuid: AzOyMyezQu***Mk8vXh1DQ)
Inserted record 32544
------------------------------_


**Using Dashboard**
 sudo -u www-data /usr/bin/php get_meeting_report.php --start=2020-12-15
_Finding meetings between 2020-12-15 to 2021-01-19T21:26:28Z
Using Dashboard API
Found 199 meetings
Found 0 webinars
Processing 199 meetings
Processing meeting 9243100980|KYmpTnHiTqCNY4+CGSuWTA== that occurred at 1608357449
Meeting does not exist locally; skipping
Processing meeting 92082980824|VHV6QUywTBm2GFNlD2AhZw== that occurred at 1608457467
Meeting does not exist locally; skipping
Processing meeting 2779318818|yw0lM8gGTQWaQJxRpf0dHA== that occurred at 1608457621
Meeting does not exist locally; skipping
Processing meeting 2779318818|3dlcG6l2RFWSb7Pcu/NZbg== that occurred at 1608460769
Meeting does not exist locally; skipping
Processing meeting 98477077125|Go1Zvl+HTeq1uaDu6ylzZg== that occurred at 1608529567
Meeting does not exist locally; skipping
Processing meeting 99937097800|k+TGrc9wRP21l/FlQXo73A== that occurred at 1608529717
Inserting zoom_meeting_details
Processing meeting 97459623276|yh5f6OkjS4+3d/OM6qw1HA== that occurred at 1608530088
Inserting zoom_meeting_details
Processing meeting 99348027146|RIPGZssdTw2wWHxw3/UWkw== that occurred at 1608530579
Inserting zoom_meeting_details
-----------------------------------------_

Works with Educational account.

**Comment by ASNi62** [comment]
Hi,

We ran the script and it worked, indeed : we can now see the sessions :)
(though we mentionned the courseid, it has run the script for all the courses in our Moodle... which doesn't matter but we wonder why).
However, we updated the plugin to display unique users instead of each of their connexion in the meeting, and it still doesn't work (as you can see in the screenshot below).
Thanks!

![image](https://user-images.githubusercontent.com/74971667/105191193-18109180-5b37-11eb-93f9-ce016a3c9def.png)

**Comment by CarlosV-Inserver** [comment]
> Hola,
> 
> Ejecutamos el script y funcionó, de hecho: ahora podemos ver las sesiones :)
> (aunque mencionamos el courseid, ha ejecutado el script para todos los cursos en nuestro Moodle ... lo cual no importa pero nos preguntamos por qué) .
> Sin embargo, actualizamos el complemento para mostrar usuarios únicos en lugar de cada una de sus conexiones en la reunión, y todavía no funciona (como puede ver en la captura de pantalla a continuación).
> ¡Gracias!
> 
> ![imagen](https://user-images.githubusercontent.com/74971667/105191193-18109180-5b37-11eb-93f9-ce016a3c9def.png)

Hello, I have also run "php zoom/cli/get_meeting_report.php --courseid=827 --start=2020-01-01" and it retrieves the sessions but it does it by connections and not by users like it does for you.
Is it its natural state or should I group sessions by user?

**Comment by almadog** [comment]
We run php mod/zoom/cli/get_meeting_report.php --start=2021-01-22 --end=2021-01-23 . Using dashboard API - did not throw any errors but it did not get the participants data expected.
Run php mod/zoom/cli/get_meeting_report.php --courseid=20519 --start=2021-01-25. Using Reports API and got the participants data as expected.

Still waiting for Zoom to provide an answer whether we have access to dashboard APIs but if the above is not throwing any errors I would assume so. We have an educational account. 

Also, do you know how many days back we can get participants data using Zoom API - is it 30days? Asking as we have missing data from more than 30 days.

Thanks.

**Comment by rlorenzo** [comment]
@almadog Yes, the limit is 30 days.

Something must be wrong with the Dashboard API then.. It is not returning the same results as the Reports API. We were running into daily limits with the Report API and the Dashboard API is more efficient. Might have to roll back using the Dashboard API if this keeps happening.

**Comment by ASNi62** [comment]
@rlorenzo Hello,
Do you have any idea what we could do / could be done ?
Teachers are now all wondering why they haven't been able to see the sessions for 1 month (we also have a educationnal licence for our university).
We have started to show them how to read these reports in Zoom, but it really is better to see them in Moodle from their course :)
Thanks

**Comment by almadog** [comment]
Thanks @rlorenzo. As per @ASNi62 question is there something we can run manually (using the reports API) to get the participants into Moodle? Can we run two 30 days periods going back to Nov 2020 or we can only go back 30 days? I have also got a better response from Zoom stating educational accounts do get the Dashboard API.

**Comment by rlorenzo** [comment]
@almadog and all you can change from using the Dashboard API (which appears to not have the session data) to the Reports API (which we used to use) by changing https://github.com/ucla/moodle-mod_zoom/blob/228d213d5bf3768914859d41ab2030132840d2c1/classes/task/get_meeting_reports.php#L144

Change

`if (!empty($hostuuids)) {`

To 

`if (true && !empty($hostuuids)) {`

Still looking into why the Dashboard API is missing data

**Comment by almadog** [comment]
Thanks @rlorenzo

**Comment by rlorenzo** [comment]
@almadog Finally found the bug. The problem was that the duration was a string and not integer from the Zoom API.

See https://github.com/ucla/moodle-mod_zoom/commit/9987cf7bc1347f17ec7a2c590a906faef2484946

**Comment by almadog** [comment]
Thanks @rlorenzo
