### ISSUE TITLE
Hosting Question

### ISSUE THREAD

**Issue by faraazandeh** [ucla/moodle-mod_zoom#176]
Hello, sorry if i'm using the wrong place to ask this question but i couldn't find any other way to contact the developers nor any data about this issue.
**Does this plugin need root access to the moodle hosting server?** it'll be important for the hosting service to know this matter.

Thanks in advance

**Comment by jrchamp** [comment]
The plugin itself doesn't need any special access, but the person installing the plugin needs to have access to install Moodle plugins.
