### ISSUE TITLE
Include phone numbers so people can call in

### ISSUE THREAD

**Issue by tomwootton** [ucla/moodle-mod_zoom#18]
The zoom meeting includes phone numbers and a link for international phone numbers for people to be able to dial into meetings. Can the plugin be updated to pull that information from zoom and present it to to users in the meeting info page?

**Comment by rlorenzo** [comment]
@tomwootton We had our developers look at the REST APIs and the phone call in information is not returnable by any means that we can obtain. That information seems to only live on Zoom's client or server end. So we cannot provide that information in Moodle. You can copy that information and put it into the description of the Zoom meeting as a workaround.

**Comment by jrchamp** [comment]
@rlorenzo Would it be possible to add a label to this that indicates that the API is missing functionality and that's why this was declined?
