### ISSUE TITLE
Differing pluginname prefix for setting zoom | requirepasscode

### ISSUE THREAD

**Issue by abias** [ucla/moodle-mod_zoom#180]
Hi all,

I noticed that the plugin admin setting 'zoom | requirepasscode' (see https://github.com/ucla/moodle-mod_zoom/blob/master/settings.php#L106) does not use the same prefix 'mod_zoom' like all other admin settings of the plugin. In fact, it's the only setting which is labeled correctly as for activity modules, the "mod_" prefix is omited for historic reasons.

You might want to fix that in settings.php and provide an upgrade steps in db/upgrade.php for existing installations.

Cheers,
Alex

**Comment by jrchamp** [comment]
Interesting find! I wonder if that's why this property_exists check was added:
https://github.com/ucla/moodle-mod_zoom/commit/12058f39721ca2fc9333a5ba1d29af06af0f05bc#diff-8f5ff72ef1cf59199cfc4bbf16f2475d09e448601242f0d2c51bb94bd4aa1395L124-R128

**Comment by rlorenzo** [comment]
Closing because https://github.com/ucla/moodle-mod_zoom/pull/197 has been merged
