### ISSUE TITLE
table zoom_meeting_participants needs an index on uuid

### ISSUE THREAD

**Issue by prigaux** [ucla/moodle-mod_zoom#184]
Cron task mod_zoom\task\get_meeting_reports
- is calling `process_meeting_reports` on each meetings
- which calls `format_participant` on each meeting participants
- which queries `zoom_meeting_participants WHERE uuid = ?`

Our `zoom_meeting_participants` is getting bigger and bigger every day (currently 350 000 rows).
To lower the database CPU used by this task, we suggest:
```sql
create index idx_zoom_rawparticipants on mdl_zoom_meeting_participants (uuid);
```

**Comment by rlorenzo** [comment]
@prigaux Thanks for the improvement suggestion. Merged fix.
