### ISSUE TITLE
Proposal: "Host" name field as Zoom.us account profile display name instead of first name

### ISSUE THREAD

**Issue by gengoac** [ucla/moodle-mod_zoom#195]
Hello. I believe the plugin displays the "Host" field as the Zoom account holder's "first" name in the zoom.us account details. Is it possible to change this to the zoom.us account profile "display name", or perhaps make it an option in the plugin settings to display either the display name, first name, last name, or first and last name.

Thank you in advance.

**Comment by jrchamp** [comment]
I don't see "Display name" in the API: https://marketplace.zoom.us/docs/api-reference/zoom-api/users/user

Was this field added recently to the web interface? I don't remember seeing it.

**Comment by gengoac** [comment]
I'm not sure of the details. I see it when I login to zoom.us and go to profile -> edit (to the right of my name).

![image](https://user-images.githubusercontent.com/78563574/107109268-db1ded80-680c-11eb-92b8-d41942908a4e.png)

**Comment by rlorenzo** [comment]
The Zoom API isn't returning the display name in their API so this is not something we can implement. But also, we should be preferring to show the name that is in Moodle.
