### ISSUE TITLE
Remove non-english language packs

### ISSUE THREAD

**Issue by abias** [ucla/moodle-mod_zoom#199]
Hi Rex,

this plugin ships with several non-english language pack in its codebase (https://github.com/ucla/moodle-mod_zoom/tree/master/lang). This seems unnecessary / counterproductive as nowadays Moodle plugins can be easily translated by everyone in AMOS (htps://lang.moodle.org).

Could you please think about removing the non-english language packs from the codebase?

Thanks,
Alex

**Comment by jrchamp** [comment]
Rex is aware of this issue and mentioned it in #133 and #149. I agree that it makes sense to remove them because AMOS is the standard way of doing this for Moodle and it helps reduce some of the maintenance burden on the plugin maintainer.

**Comment by abias** [comment]
Thank you, @jrchamp , for this response.
I was not aware of these comments as both predate our usage of this plugin.

**Comment by rlorenzo** [comment]
Removed language packs in https://github.com/ucla/moodle-mod_zoom/commit/89177e387298b1a104a01cf068764a27bdbc42f2
