### ISSUE TITLE
Get meeting reports misses meetings that start before and end after cron task

### ISSUE THREAD

**Issue by haietza** [ucla/moodle-mod_zoom#203]
The session reports that are pulled back into Moodle with the get_meeting_reports scheduled task do not get the data for meetings that start before the cron task but finish after. 

For example, on our system the cron task runs every 6 hours (12am, 6am, 12pm, 6pm). We have regular Zoom meetings that start at 10:45am and finish at 12:15pm. The cron task is set to pull meetings with start times within the past 6 hours (or the last time the cron task was run), so the 12pm run will attempt to get the meeting reports for the 10:45am meeting, however it won't be available because it has not finished yet. The next run of cron at 6pm will not attempt to get that meeting report, since the start time is before the last run of cron at 12pm. 

Would it be better to filter events for processing by the end time instead of the start time, so these meetings would not be missed?

Thank you!

**Comment by rlorenzo** [comment]
@haietza Thanks for the logic fix suggestion. Done here https://github.com/ucla/moodle-mod_zoom/commit/735ff923d8434dc8e75fc6f5fad2d9972ef3afc9
