### ISSUE TITLE
Moodle zoom report and moodle report from website are different

### ISSUE THREAD

**Issue by Maniuz** [ucla/moodle-mod_zoom#204]
In some cases the zoom report on moodle is very different from the one I download from the zoom site.
For example on the one present in moodle there is no presence of some users, as if they had never connected.
This makes the data from the moodle zoom report unreliable.

**Comment by rlorenzo** [comment]
@Maniuz The Moodle Zoom reporting missing some users was due to an error the code that downloaded the meeting reports. It was recently fixed in https://github.com/ucla/moodle-mod_zoom/commit/0bf560438874d6d8c66e1e9078698e417f5f3212
