### ISSUE TITLE
This would only erase the cache of the last course added to the array

### ISSUE THREAD

**Issue by fabianbatioja** [ucla/moodle-mod_zoom#21]
The value of each element of the array is 1, therefore the array_flip() always returns an array with the last element added.

that should work like this?

https://github.com/ucla/moodle-mod_zoom/blob/ff0c8c8a8805f2156cf9f2ffc2a42753eee322bf/locallib.php#L322-L325

**Comment by rlorenzo** [comment]
@fabianbatioja This is now fixed in our latest development branches. The code will be merged to master soon and a new version released.
https://github.com/ucla/moodle-mod_zoom/blob/development/classes/task/update_meetings.php#L116
