### ISSUE TITLE
"Recreate meeting" function does not update all necessary DB fields

### ISSUE THREAD

**Issue by nstefanski** [ucla/moodle-mod_zoom#210]
We've had several instances lately where our Zoom meetings were deleted in Zoom. When the users used the link to "recreate" the meeting on Zoom, neither students or instructors were able to launch the meeting.

Digging in, I see that `recreate.php` only updates the DB fields for the `meeting_id` and the `timemodified`. The `join_url` and `start_url` are not updated in Moodle, so any features that utilize those urls attempt to send the users to invalid meetings. Also, the field `exists_on_zoom` is never updated to show that the meeting has been restored.

It seems like this could be simply fixed by using the lib function `populate_zoom_from_response()` instead of manually changing only two fields?

**Comment by rlorenzo** [comment]
@nstefanski Thanks for the bug report. Fixed in https://github.com/ucla/moodle-mod_zoom/commit/37cd1b92700d51390c1255b07dabb6e00882aa3f
