### ISSUE TITLE
Cron only report info about day´s reports

### ISSUE THREAD

**Issue by Hser2bio** [ucla/moodle-mod_zoom#213]
Hi sir!

im checking and force updating reports from console executing the cron, and bring me the info correctly, but only bring me the info of day´s meeting that i execute the command. 

could be that configurable? 

thanks in advance

**Comment by rlorenzo** [comment]
@Hser2bio  The cron updates from the last time it ran.

To run for any date range use this command line script https://github.com/ucla/moodle-mod_zoom/blob/master/cli/get_meeting_report.php

**Comment by Hser2bio** [comment]
thanks works :)
