### ISSUE TITLE
PHPUnit error - test_delete_module_delete_events

### ISSUE THREAD

**Issue by aspark21** [ucla/moodle-mod_zoom#215]
Moodle - 3.9.4+ (latest)
Zoom - master @ 903776c
Unfortunately plugin CI only runs unit tests for the plugin and not the full suite of core tests. The following is broken as I've just completed a full run in preparation for 3.9.5 coming out next week.

core_calendar_container_testcase::test_delete_module_delete_events
    moodle_exception: Zoom webservice error: Zoom API key not found.
  
    /var/www/html/mod/zoom/classes/webservice.php:126
    /var/www/html/mod/zoom/lib.php:70
    /var/www/html/course/modlib.php:128
    /var/www/html/lib/testing/generator/module_generator.php:271
    /var/www/html/mod/zoom/tests/generator/lib.php:63
    /var/www/html/calendar/tests/container_test.php:445
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "core_calendar_container_testcase" calendar/tests/container_test.php

**Comment by abias** [comment]
Hi @aspark21 ,

I am the one who contributed 903776c which just made some changes to the way how the plugin settings are stored in the DB. I would like to preclude that this patch isn't the one which broke the test.
Would you mind to re-run the test suite just with the commit before (881bee2c6eee433bfd1d7e6759256b4ccc7a9553) to see if the problem persists or disappears?

As an addition, looking at https://github.com/ucla/moodle-mod_zoom/blob/master/tests/generator/lib.php, I see that there are several plugin settings made in the mock of the plugin. But there isn't an API key set. 
So I am wondering about two things and would like to ping @rlorenzo about that:
a) is the API key missing there by purpose?
b) I didn't add anything to this mock when I added new admin settings during the last weeks. Do you want me to add them there?

Thanks,
Alex

**Comment by aspark21** [comment]
Running it now with 881bee2 

Have gone back through our previous runs, the test definitely did not fail on 3rd Feb. Our other runs since are polluted by other issues so can't really pinpoint it any further. So 228d213 was clean and this was introduced afterwards.

**Comment by jackvanb** [comment]
This is caused by my PR #209, as the test module generator was added. Adding these [two lines](https://github.com/ucla/moodle-mod_zoom/pull/209/files#diff-d2d9729f5e9e38e2ae85a1ade94914dd48d78e6e690e837343ddf7988909ed41R45) to /mod/zoom/tests/generator/lib.php should fix this issue.

I am unable to work on this today, but can tomorrow.

**Comment by aspark21** [comment]
Confirmed this was in 881bee2 run
