### ISSUE TITLE
Error creating webinar

### ISSUE THREAD

**Issue by dbfiore** [ucla/moodle-mod_zoom#218]
If a meeting is created as a webinar, there is no visible problem until visiting the activity page in Zoom, then everyone gets the following error:
```
Zoom received a bad request: Cannot access webinar info.
line 601 of /mod/zoom/classes/webservice.php: call to debugging()
line 73 of /mod/zoom/view.php: call to mod_zoom_webservice->get_meeting_invitation()
```
Running Moodle 3.10, mod_zoom 3.4.  Logged in to moodle with an account whose zoom privs include the ability to create webinars (user's email in Moodle matches email for Zoom user with webinar privs).

**Comment by rlorenzo** [comment]
@dbfiore Thanks for the report. Fixed in https://github.com/ucla/moodle-mod_zoom/commit/3bcba8ce07d06e5710231a4d27fd54601f010f43

**Comment by dbfiore** [comment]
Is there a way for me to get an updated build?

Thanks!
-dbf

David Fiore
***@***.***

"The grass withers, the flower fades,
but the word of our God will stand forever.”  Isaiah 40:8

**Comment by rlorenzo** [comment]
@dbfiore New version released: https://moodle.org/plugins/pluginversion.php?id=23677

**Comment by dbfiore** [comment]
Ahh, yes.  Installed it.  Thanks!


BTW, is there a good resource for getting started writing moodle mods?

Thanks!
-dbf

David Fiore
***@***.***

"The grass withers, the flower fades,
but the word of our God will stand forever.”  Isaiah 40:8

**Comment by rlorenzo** [comment]
@dbfiore Please see the "Moodle Plugin Development Basics" course at https://learn.moodle.org

It is free to view.
