### ISSUE TITLE
Session duration in seconds

### ISSUE THREAD

**Issue by Filaretis** [ucla/moodle-mod_zoom#220]
Hi, there!
The session duration in reports is now calculated in seconds, but logically it should be in minutes.

![image](https://user-images.githubusercontent.com/76186274/110152244-89a85480-7df2-11eb-9903-c456fd7f7dd5.png)

**Comment by rlorenzo** [comment]
@Filaretis Thanks for testing out the latest changes. Fixed in https://github.com/ucla/moodle-mod_zoom/commit/5f520436ca520a144584b6cac6ce1c4ecb60ba60
