### ISSUE TITLE
Error creating meeting

### ISSUE THREAD

**Issue by dbfiore** [ucla/moodle-mod_zoom#226]
I just updated to the latest mod/zoom and tried to create a meeting.  Got the message below.  When I logged back in, I saw that the meeting was created.

Notice: Undefined property: stdClass::$webinar in /opt/bitnami/apps/moodle/htdocs/mod/zoom/classes/webservice.php on line 582

Notice: Undefined property: stdClass::$webinar in /opt/bitnami/apps/moodle/htdocs/mod/zoom/classes/webservice.php on line 531
Skip to main content
This page should automatically redirect. If nothing is happening please use the continue link below.
(Continue)

Error output, so disabling automatic redirect.

**Comment by rlorenzo** [comment]
@dbfiore Seems there is some code cleanup to do, must be related to a change done in https://github.com/ucla/moodle-mod_zoom/pull/200

But if you have debugging turned off and PHP notices suppressed, it shouldn't be a problem in production.

**Comment by abias** [comment]
I am sorry if this flaw was triggered by my change in #200.

I will try to submit a PR with a fix soon.

**Comment by jrchamp** [comment]
@dbfiore To reinforce what @rlorenzo said: It is strongly recommended to have debugging off for production systems.

**Comment by rlorenzo** [comment]
Closing. Fixed in master
