### ISSUE TITLE
Version 3.5 not compatible on Moodle versions lower than 3.7

### ISSUE THREAD

**Issue by keevan** [ucla/moodle-mod_zoom#227]
Release 3.5 of this plugin not compatible on any Moodle version lower than 3.7 due to hide_if method not being added until MDL-52167 (https://github.com/moodle/moodle/commit/8ed3671d4cd883bf13754234d339243ec2c4be57) despite plugin version compatibility supporting all versions (https://moodle.org/plugins/pluginversions.php?plugin=mod_zoom), which appears during an upgrade.

Exception - Call to undefined method admin_settingpage::hide_if()

Stack trace:

    line 115 of /mod/zoom/settings.php: Error thrown
    line 89 of /lib/classes/plugininfo/mod.php: call to include()
    line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
    line 7999 of /lib/adminlib.php: call to require()
    line 22 of /admin/upgradesettings.php: call to admin_get_root()

**Comment by abias** [comment]
I am sorry about this failure as it was me who contributed the admin setting page changes.

I will submit a PR with a fix soon.
