### ISSUE TITLE
Lost Moodle site Administrator access after installing zoom plugin

### ISSUE THREAD

**Issue by Sergio-Cardoso** [ucla/moodle-mod_zoom#231]
After installing zoom plugin on moodle (3.5.0) got an error " Web do Zoom service error:  Zoom API Key not found" and  then when trying to access Site Administrator menu t o uninstall the pluggin got the error: "Exception - Call to undefined method admin_settingpage::hide_if()

Now I can´t access the site administrator.  Try to to use the login as admin but after login can´t find a path or a way to uninstall the plugin.  I am out of town and will not have access to the server during this week.  is there a way to fix this?

**Comment by rlorenzo** [comment]
@Sergio-Cardoso Fixed in https://github.com/ucla/moodle-mod_zoom/commit/d6f5c740fdef894bfe8db9490b40dd45386158f2

**Comment by Sergio-Cardoso** [comment]
Thank you!  everything is working fine now!!!
