### ISSUE TITLE
Mobile app does not update "view" completion criteria

### ISSUE THREAD

**Issue by nstefanski** [ucla/moodle-mod_zoom#237]
It was brought to my attention that the mobile app does not update the "view" completion criterion in Moodle, it just assigns a grade if the meeting is set to be gradable. The view completion code in `loadmeeting.php` just needs to be copied into the webservice in `external.php`, I'll open a new pull request shortly.

**Comment by rlorenzo** [comment]
Merged in https://github.com/ucla/moodle-mod_zoom/pull/238
