### ISSUE TITLE
Troubles with non recurring meeetings

### ISSUE THREAD

**Issue by ASNi62** [ucla/moodle-mod_zoom#241]
Hi,
 since the last update we have troubles with non recurring meetings.
 We can use the plugin to create recurring ones, but when we add non recurring meetings, here is the message : 
 
Exception : Argument 1 passed to zoom_get_unavailability_note() must be an instance of object, instance of stdClass given, called in [dirroot]/mod/zoom/view.php on line 203

The meeting IS created in zoom, however it can't be joined via Moodle, which is really annoying.

Is there anything we can do?
Thanks.

**Comment by rlorenzo** [comment]
@ASNi62 I cannot reproduce this problem. I can create a specific non-recurring meeting and join as an instructor or student.

@jrchamp @abias Have you seen any issues with the current Zoom plugin for non-recurring meetings?

**Comment by jrchamp** [comment]
I find `must be an instance of object, instance of stdClass given` concerning.

The type is specified here: https://github.com/ucla/moodle-mod_zoom/blob/c16e203235053fb602854591b71f6c8877c091ec/locallib.php#L670

Sorry, I didn't see this change and it unnecessarily increased the minimum version of PHP. @ASNi62 is probably running PHP 7.0 or 7.1.

**Comment by rlorenzo** [comment]
@jrchamp Unfortunately I cannot get the GitHub actions to automatically test using PHP 7 or 7.1.

If we change the parameter to be stdClass instead of object would it work? We don’t have PHP 7 or 7.1 easily setup to test.

@ASNi62 What is your PHP and Moodle version?

**Comment by jrchamp** [comment]
@rlorenzo I created #244 which should allow us to do static analysis of PHP compatibility. The config value `testVersion` can be given a range and that allows us to set the minimum supported version. Fun fact: at this time, three `void` return types (thankfully only in tests) and the `object` argument type are the only things preventing PHP 7.0 compatibility.

Yes, changing the parameter to be `stdClass` instead of `object` or removing the `object` type as I did in #243 would both solve the problem.

**Comment by ASNi62** [comment]
Here is our Moodle version : 3.8.4
PHP version : 7.1.33

Thanks!

**Comment by rlorenzo** [comment]
@ASNi62 If you are able to, you can run the latest version in the master branch and it should fix your problem.

**Comment by abias** [comment]
As I was the one who added these lines of code, I am sorry for the caused hickup.
And I agree that, if the plugin is really required to work on legacy PHP versions, the change in #243 is fine.
