### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by sheldon65** [ucla/moodle-mod_zoom#25]
I am attempting to install plugin from with moodle 3.3.  On install via plugin section in Moodle I get an error that unittest is missing on disk.  Also a list of about 20 themes names that show to be deleted.  Please help advise how to proceed.  

This is a clean install of moodle on cpanel.

![capture](https://user-images.githubusercontent.com/35608616/35164264-5594fc50-fd0f-11e7-9769-029b36da9904.JPG)

**Comment by sam-suresh** [comment]
@sheldon65 This is nothing to do with this plugin. It seems your themes were missing. You can uninstall it if you are not using it.

**Comment by rlorenzo** [comment]
@sheldon65 Yes, that is not related to the Zoom plugin. It also happens on our Moodle install. It is safe to ignore.
