### ISSUE TITLE
Why cant zoom meeting start on a new window tab

### ISSUE THREAD

**Issue by tjr007ma** [ucla/moodle-mod_zoom#26]
Is there a way to make the zoom meeting to start in a new window? every time the meeting is clicked on, it loads on top of moodle. Users will have to open a new window and log into moodle again.

**Comment by Nicosoft** [comment]
Hi there,

Yes, by default the start meeting is opened in the same page.
Have you tried to hold "Shift" button and click on 'Start Meeting'? it should open the meeting in a new tab.
Otherwise this change required a code change.

**Comment by rlorenzo** [comment]
@tjr007ma This is done in our latest development branch and will be merged to master soon and included in the new release: https://github.com/ucla/moodle-mod_zoom/blob/development/view.php#L126

**Comment by cdipe** [comment]
We are using v2.0.1, 2018092200
There are two different results with this depending on whether the participant selects the **Start meeting** button (starts in a new window) or the **Join link** (starts current/same window).
![zoom window](https://user-images.githubusercontent.com/14754240/48404618-e9195c80-e730-11e8-9544-c99358bd4d03.png)

**Comment by erickuncoroeworks** [comment]
This is brilliant! thank you Rex!

@cdipe thanks for sending the screenshot too.
