### ISSUE TITLE
Does not support Privacy API

### ISSUE THREAD

**Issue by thepurpleblob** [ucla/moodle-mod_zoom#33]
Could this be extended to support the new Privacy API please?

**Comment by rlorenzo** [comment]
@thepurpleblob Would you be able to help us test this? https://github.com/ucla/moodle-mod_zoom/tree/patch/CCLE-7359-Make-Zoom-GDPR-Compliant

**Comment by rlorenzo** [comment]
@thepurpleblob This is done in our latest development branch and will be in our new version soon: https://github.com/ucla/moodle-mod_zoom/tree/feature/CCLE-7359-Make-Zoom-GDPR-Compliant
