### ISSUE TITLE
More default configurations

### ISSUE THREAD

**Issue by cdipe** [ucla/moodle-mod_zoom#34]
We would really like for the following default settings to be configurable on site level:

- Recurring
- Host video on/off
- Participants video on/off
- Audio options
- Meeting option

**Comment by rlorenzo** [comment]
@cdipe This has been done in https://github.com/ucla/moodle-mod_zoom/commit/b5014bdca13b805845c7ecffeb5b4ca728cf016b and will be included in the next release of the plugin.

**Comment by cdipe** [comment]
Great, thanks!

**Comment by cdipe** [comment]
Also, a checkbox for opening the meeting in a new window would be very handy!
