### ISSUE TITLE
zoom stopped on launching page, not loading.

### ISSUE THREAD

**Issue by ypshukla** [ucla/moodle-mod_zoom#36]
After creating an activity in moodle, when click to start a meeting, the below page opens & stopped at the same:

![screenshot from 2018-07-23 14-12-13](https://user-images.githubusercontent.com/36185596/43066487-6aabd10e-8e82-11e8-9f83-57ac3c414ba9.png)

I am using the Cent OS 7 & installed the supported .rpm package from zoom website & also installed the zoom chrome extension. I configured the External tool as per [zoom moodle documentation](https://support.zoom.us/hc/en-us/articles/201363313-Configuring-LTI-with-Moodle)

**Comment by rlorenzo** [comment]
@ypshukla Sorry, but this screenshot now shows the issue is on Zoom's end and not the plugin anymore. The Moodle plugin just sets up the meeting and directs you to Zoom's servers. Please contact https://support.zoom.us/hc/en-us
