### ISSUE TITLE
Error in webservice

### ISSUE THREAD

**Issue by lostrowhite** [ucla/moodle-mod_zoom#39]
I found a problem when you set the license number and utmost in the plugin settings show the message error: Zoom utmost setting found but, licenses count setting not found. Then looking for i found in the class mod_zoom_webservice on line 102 you compare $config->licensescount but there is not defined. I think that you need compare with $config->licensesnumbe. Please let me know if i was in mistake.

**Comment by jrchamp** [comment]
Looking at the code, it looks like @lostrowhite is correct.

@rlorenzo If you do end up moving forward with $config->licensesnumber, you may want to change the error string to match the setting: https://github.com/ucla/moodle-mod_zoom/blob/067e0924b38c495eb016272ce498fe5242f1220c/lang/en/zoom.php#L150

**Comment by rlorenzo** [comment]
Is this still an issue? I am closing since we revamped this code since then in https://github.com/ucla/moodle-mod_zoom/commit/32081ae460eb7ee880c599fde51e194de1f8a718
