### ISSUE TITLE
Enable Join Before Host not working

### ISSUE THREAD

**Issue by antosr** [ucla/moodle-mod_zoom#4]
Recently began using Zoom platform with the most recent plugin.  Creation of Zoom activity with option checked 'Enable Join Before Host' does not create the meeting with that option.

**Comment by antosr** [comment]
Just to confirm, creating similar meeting within Zoom client with same options does create the meeting correctly.

**Comment by rlorenzo** [comment]
Yeah, we patched that bug on the latest master branch, but have yet to update the Moodle plugin database with the latest zip.

See bce4a90a4737e926f39944dbecf91f2d6f0f7b19

**Comment by rlorenzo** [comment]
Patch was completed in v1.4.

**Comment by suneetakunwar-paradiso** [comment]
I am still not able to join with JBH option enabled.
Did the changes as suggeted.
Using moodle 2.7 .Can you please help me?

**Comment by jrchamp** [comment]
> I am still not able to join with JBH option enabled.
> Did the changes as suggeted.
> Using moodle 2.7 .Can you please help me?

I ran into a similar issue, so hopefully this helps: You'll need to make sure you can enable Join Before Host directly in Zoom, because it might be locked off in your account.
