### ISSUE TITLE
Request for enhancement: another option for 'Activity completion'

### ISSUE THREAD

**Issue by bparry13** [ucla/moodle-mod_zoom#43]
When you create a new ZOOM activity, the only option you have for Activity completion is 'Student must receive a grade to complete this activity'.

Currently we host Moodle for multiple clients, and we are getting requests to add an option for 'Activity completion'. The option requested is 'Student must view this activity to complete it'.

The teachers say they are not using the Zoom session for grading, but more as evidence of participation in the course.

**Comment by jrchamp** [comment]
+1 This seems like a valuable change. If I read the documentation correctly, this may be easy to implement: https://docs.moodle.org/dev/Activity_completion_API#Completion_on_view

**Comment by gsyoung** [comment]
+1 From me too. Zoom/ webinars within are mostly about activities not Grading. The 'Viewed activity' is a little more about confirming who did/didn't participate in the webinar. Having both options is the best and most functional outcome.

**Comment by nstefanski** [comment]
I think one potential pitfall of completion on view is that a student can just view the page with the meeting information and never join the meeting. A better analogy might be the Moodle assignment: students can view the assignment, make a submission, and receive a grade for the assignment, and each of these three is a possible completion setting. Moodle also has information on how to add a custom completion setting similar to the assignment submission: https://docs.moodle.org/dev/Activity_completion_API#Custom_completion_rules

**Comment by rlorenzo** [comment]
Fixed in https://github.com/ucla/moodle-mod_zoom/pull/118
