### ISSUE TITLE
Feature request: Include upcoming meetings in users' Timeline

### ISSUE THREAD

**Issue by matturn** [ucla/moodle-mod_zoom#48]
It would be good if upcoming Zoom meetings were included in enrolled users' Timelines on their Dashboard.

The ability for Moodle to send a reminder message to enrolled users would be good too.

Both might be options with a default set to "on".

**Comment by RadBoris** [comment]
Hi @rlorenzo, 

I can submit a PR by early next week that solves the timeline display issue for upcoming meetings but wanted to confirm that sending reminders is also something that you would like to be included. If yes, I will need a bit more time.

**Comment by rlorenzo** [comment]
@RadBoris We don’t use timeline in our Moodle so whatever you feel most users would want or fine useful is fine.

**Comment by rlorenzo** [comment]
This has now been implemented in https://github.com/ucla/moodle-mod_zoom/pull/169
