### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by ayhan01** [ucla/moodle-mod_zoom#5]
It gives the following error when installing the plugin:

mod_zoom

DDL sql execution error

More information about this error
Debug info: Table 'mdl_zoom' already exists
CREATE TABLE mdl_zoom (
id BIGINT(10) NOT NULL auto_increment,
course BIGINT(10) NOT NULL,
intro LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
introformat SMALLINT(4),
grade BIGINT(10),
uuid VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
meeting_id BIGINT(10) NOT NULL,
start_url LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
join_url LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
created_at VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci,
host_id VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
name VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
start_time BIGINT(12),
timemodified BIGINT(12),
type TINYINT(1) NOT NULL DEFAULT 1,
duration MEDIUMINT(6),
timezone VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci,
password VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci,
option_jbh TINYINT(1) DEFAULT 0,
option_start_type VARCHAR(12) CHARACTER SET utf8 COLLATE utf8_general_ci,
option_host_video TINYINT(1) DEFAULT 1,
option_participants_video TINYINT(1) DEFAULT 1,
option_audio VARCHAR(9) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'both',
status TINYINT(1),
CONSTRAINT PRIMARY KEY (id)
, KEY mdl_zoom_mee2_ix (meeting_id)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE = utf8_general_ci
COMMENT='Zoom meetings'
Error code: ddlexecuteerror
Stack trace:

    line 449 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
    line 905 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 76 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
    line 412 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
    line 364 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
    line 671 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
    line 424 of /lib/upgradelib.php: call to upgrade_plugins_modules()
    line 1630 of /lib/upgradelib.php: call to upgrade_plugins()
    line 433 of /admin/index.php: call to upgrade_noncore()

**Comment by rlorenzo** [comment]
@ayhan01 The error is "Table 'mdl_zoom' already exists". You will need to go into your database and delete the mdl_zoom table and retry the install.
