### ISSUE TITLE
uaser_autocreated method undefined error in unit tests

### ISSUE THREAD

**Issue by danmarsden** [ucla/moodle-mod_zoom#55]
this is on a 3.7 (master) branch - so not sure if it's something new...

1) createuser_test::test_user_autocreate_false
Error: Call to undefined method Mock_mod_zoom_webservice_d1f21bc9::user_autocreate()

/var/www/html/mod/zoom/tests/createuser_test.php:93
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "createuser_test" mod/zoom/tests/createuser_test.php

2) createuser_test::test_user_autocreate_existing
Error: Call to undefined method Mock_mod_zoom_webservice_d1f21bc9::user_autocreate()

/var/www/html/mod/zoom/tests/createuser_test.php:111
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by rlorenzo** [comment]
@danmarsden Yeah, that is an old test. We should be deleting it soon.
