### ISSUE TITLE
fails to install in Moodle 3.7

### ISSUE THREAD

**Issue by danmarsden** [ucla/moodle-mod_zoom#56]
Due to changes that landed in master this week (MDL-62599) JWT is now in core so mod_zoom no longer installs due to a conflict with the core JWT lib.

Fatal error: Cannot declare class Firebase\JWT\JWT

I'll file a pull request for this but it might mean you need to branch to support Moodle 3.7 rather than supporting multiple versions in your master branch (better than keeping the old JWT lib in your codebase...)

**Comment by jrchamp** [comment]
Thank you for highlighting this change in core. For now, a lightweight change that doesn't remove compatibility with the currently supported versions of Moodle would help with the transition. It's not as elegant, but adding another `file_exists` check that targets the JWT library in core might be sufficient. Adding a comment to remove the file_exists checks and JWT library after we no longer support versions of Moodle prior to 3.7 would make future cleanup simple.

**Comment by danmarsden** [comment]
cool - feel free to close the pull request and fix it the way you want to - personally I prefer to branch rather than maintaining the technical debt but understand that some people prefer to manage their plugins with a single branch.

**Comment by ertheosiswadi** [comment]
@danmarsden Hi Dan, I'm a UCLA student developer. I installed Moodle 3.7 and then successfully installed ZOOM. I see that there is JWT in both lib and mod but I couldn't seem to reproduce your error and it runs just fine. Could you please elaborate more on how you got the error? I might be understanding it incorrectly. Thank you

**Comment by rlorenzo** [comment]
Fixed in https://github.com/ucla/moodle-mod_zoom/commit/2b3e7e858169ec12a2022c9479613755de1d1ddb
