### ISSUE TITLE
DB Schema is not consistent with upgrade.php

### ISSUE THREAD

**Issue by tuanngocnguyen** [ucla/moodle-mod_zoom#58]
Hi

The column "start_time" (table zoom_meeting_details) is not in sync between install.xml and upgrade.php

null value instead of XMLDB_NOTNULL
https://github.com/ucla/moodle-mod_zoom/blob/master/db/upgrade.php#L208

Not null = true
https://github.com/ucla/moodle-mod_zoom/blob/master/db/install.xml#L48

**Comment by rlorenzo** [comment]
Accepted pull request https://github.com/ucla/moodle-mod_zoom/pull/59
