### ISSUE TITLE
Error "First Time User"

### ISSUE THREAD

**Issue by matiasrosemberg** [ucla/moodle-mod_zoom#6]
Hi, I get this error message when trying to create a new zoom activity: 

"You are using Zoom for the first time, so you must enable your Zoom account by logging in to with your login credentials. Once you've activated your Zoom account, reload this page and continue setting up your meeting."

But, I already created a new account, I already validate it and I have configured mi app key and secret key.

Any ideas?

**Comment by rlorenzo** [comment]
Make sure that the Zoom account has the same email address as the Moodle user you are trying to login with. That is how we connect users between the two systems.
