### ISSUE TITLE
Zoom Icon needs to be scaled down

### ISSUE THREAD

**Issue by stopfstedt** [ucla/moodle-mod_zoom#60]
In the "Recently Accessed Items" block, the icon breaks layout.

![zoom svg recently accessed items](https://user-images.githubusercontent.com/1410427/59936358-a88b6b00-9404-11e9-87ff-e0660d9400b6.png)

**Comment by stopfstedt** [comment]
PR is forthcoming shortly.

**Comment by jrchamp** [comment]
It looks like the width of the icon is not being set by the block. The icon is intended to be full width, so the container needs to set the width.

**Comment by rlorenzo** [comment]
@jrchamp We don't use the "Recently Accessed Items" block, but is the setting of the width we can do in our plugin code? What callback would be used? Or is Moodle assuming all icons are 24 px width?

**Comment by stopfstedt** [comment]
@rlorenzo moodle is assuming the pixel width of 24px. our current workaround is to apply explicit styles in our custom theme (sub-theme of boost).

the Moodle docs appear to back this up as well. https://docs.moodle.org/dev/Moodle_icons

**Comment by rlorenzo** [comment]
Fixed in new release
