### ISSUE TITLE
Response message: User not belong to this account

### ISSUE THREAD

**Issue by redgumriver** [ucla/moodle-mod_zoom#64]
We've recently encountered a number of instances where users are receiving the following Exception when trying to join meetings: Zoom webservice error: User not found on this account

This seems to be caused by a 400 response to the https://api.zoom.us/v2/users/{email} request which for certain users returns:

{
    "code": 1010,
    "message": "User not found on this account"
}

It is possible the Zoom API has changed recently replacing the similar "not belong to this account" message with the above. If this is the case, perhaps the plugin should check for the 1001/1010 response codes instead of the message text.

**Comment by jrchamp** [comment]
This will be resolved by #63 in commit: fcc3773

**Comment by rlorenzo** [comment]
Pull request #63 has been merged to master
