### ISSUE TITLE
Speed rate limit-error

### ISSUE THREAD

**Issue by simpasam** [ucla/moodle-mod_zoom#67]
Can't create Zoom sessions more than once. Getting this speed rate limit error. This limit is 10/sec in Zoom

**Comment by rlorenzo** [comment]
That is a limitation of the Zoom API. See https://marketplace.zoom.us/docs/api-reference/rate-limits

We have an educational account so that increases the number of API calls we can make. I would suggest reaching out to Zoom support to see what they can do about the API limits for your account.
