### ISSUE TITLE
Heads up: v1 EOL, New API Limits and Page Tokens

### ISSUE THREAD

**Issue by jrchamp** [ucla/moodle-mod_zoom#69]
Summary: Mostly an FYI, but there is an important TODO regarding the new `next_page_token`.

From https://marketplace.zoom.us/docs/guides/announcements#rate-limit-changes

- v1 APIs End of Life: April 26, 2020 (already resolved, but it means that people using older versions of this plugin will need to update)
- Rate Limit Changes: March 2020
  - Mostly these are increases, but /v2/metrics was decreased (does not appear to be used by this plugin at the moment); might want to increase `MAX_CALLS`
  - New headers like `Retry-After` as part of 429 rate limit responses
- New field for pagination `next_page_token` being rolled out over the next three months
  - _make_paginated_call() will need to be updated to use that when available instead of page_number
  - "Once all of the above APIs have support for `next_page_token`, you will have a six (6) month period to migrate from `page_number` to `next_page_token`. After the six month adoption window, the page_number field will no longer operate." So if they finish in May, then people will need to upgrade before November or it will break. We'll probably want to have a fixed version tagged and available for people in the next couple months once we can test the functionality so people will have time to upgrade.

**Comment by rlorenzo** [comment]
The next_page_token seems straightforward to implement, but the Retry-After and Rate limit change is going to be complex, I imagine. I see some people already running into it in the comments at https://moodle.org/plugins/mod_zoom

@jrchamp Thoughts or bandwidth to implement how to handle it?

**Comment by jrchamp** [comment]
Right now, I only do a `sleep(1)` if I get a 429 response and I haven't seen more than a couple. Usually, I'm hitting the server as fast as the previous call completes and the rate limit hasn't been a problem.

As far as a friendly solution, I think it depends on how long we are okay keeping people waiting.

1. In a do-while loop { Try to make the call.
2. If we were rate limited, check to see how long we need to wait.
3. If we need to wait too long, give them an error (telling the user when to come back).
4. If we don't need to wait that long, wait until then and try again.

The "waiting too long" part should be defined outside of the do-while so we can guarantee a maximum of 5, 10 or 30 seconds depending on how long is reasonable (either configurable by Moodle admin or as a part of the __make_call() function call).

**Comment by rlorenzo** [comment]
@jrchamp This is the plan that I am thinking of following:

1. Remove MAX_CALLS
2. When REST call fails check for 429 error
3. Should return following headers back:
    * X-RateLimit-Limit: 30000
    * X-RateLimit-Remaining: 10000
    * Retry-After: 2019-10-31T00:00:00Z
4. If next Retry is a minute or less, Sleep until Retry-After
5. Else, update “last_call_made_at” so get_meetings knows when to resume processing

**Comment by jrchamp** [comment]
I think that's reasonable. The minute wait might be interesting if people are trying to schedule a new meeting (web response time), but on the other hand it's only a minute.

**Comment by rlorenzo** [comment]
The minute for next re-try should only affect the Heavy reports. It seems the retries for normal web service calls is only a second.

**Comment by lneoj** [comment]
> Right now, I only do a `sleep(1)` if I get a 429 response and I haven't seen more than a couple. Usually, I'm hitting the server as fast as the previous call completes and the rate limit hasn't been a problem.
> 
> As far as a friendly solution, I think it depends on how long we are okay keeping people waiting.
> 
> 1. In a do-while loop { Try to make the call.
> 2. If we were rate limited, check to see how long we need to wait.
> 3. If we need to wait too long, give them an error (telling the user when to come back).
> 4. If we don't need to wait that long, wait until then and try again.
> 
> The "waiting too long" part should be defined outside of the do-while so we can guarantee a maximum of 5, 10 or 30 seconds depending on how long is reasonable (either configurable by Moodle admin or as a part of the __make_call() function call).

Hi jrchamp,
I am using MDL3.8 and Zoom latest version 2019080100 I really do like the workaround but as I am not code guru I have no idea where to do the wait sequence. At the moment every time I want to create Zoom Activity I need to wait around 20 sec before hit "Save and return to course" otherwise I get API rate limit. Is it possible you guys to navigate us how to temporary resolve this issue?

Many thanks!

**Comment by jrchamp** [comment]
@lneoj Sorry, I'm not sure why waiting 20 seconds solves the problem for you. My workaround would have been to reset the calls_left configuration, but if your number of calls is exhausted, it should fail all the time. I'm not able to reproduce the issue you are experiencing.

**Comment by rlorenzo** [comment]
The API limit feature is now on master: https://github.com/ucla/moodle-mod_zoom/commit/e88f877e9716f324c2ad437a015f6f3fa7217123

**Comment by jrchamp** [comment]
The only piece left from this is the `page_number` to `next_page_token` changes. On June 28, they announced the availability for most if not all of the method and the associated deprecation (without a date, but I wouldn't expect more than the 6 months they referenced originally):

> Deprecated the “page_number” field and replaced it with “next_page_token” in the Batch List APIs. Please refer to our Batch List APIs guide for details
> 
> GET /v2/accounts
> GET /v2/meetings/{meetingId}/recordings/registrants
> GET /v2/h323/devices
> GET /v2/im/groups/{groupId}/members
> GET /v2/users/{userId}/meetings
> GET /v2/meetings/{meetingId}/registrants
> GET /v2/users/{userId}/webinars
> GET /v2/webinars/{webinarId}/registrants

They also changed the pagination documentation URL: https://marketplace.zoom.us/docs/api-reference/pagination

**Comment by rlorenzo** [comment]
@kubilayagi  Has a ticket right now in our internal ticket system to work on the next page token.

**Comment by rlorenzo** [comment]
@jrchamp Our developer @kubilayagi has a patch for the next_page_token handling based on your feedback: https://github.com/ucla/moodle-mod_zoom/commit/a43d7a63a5ce2585e053896252cb40064c57a13b

**Comment by rlorenzo** [comment]
Final piece closed in https://github.com/ucla/moodle-mod_zoom/commit/28bb0f8e0e17ec6f4e353267fd9ddb3dd6ffe535

**Comment by jrchamp** [comment]
From the most recent API updates, it appears that the remaining APIs with pagination have been updated:
> Added a new field (“next_page_token”) in List Users, List Group Members, List Role Members APIs.
