### ISSUE TITLE
Connection status: Connection failed: Access token is expired.

### ISSUE THREAD

**Issue by mhughes2k** [ucla/moodle-mod_zoom#71]
After installing this module on a Moodle 3.6.4 instance (both the 2.2 2019080100 version and master) and setting up the a JWT app on zoom, the settings page comes back with:

> Connection status: Connection failed: Access token is expired.

I've noted that this has been mentioned a couple of times on the Moodle Plugin page for this module.

Michael

**Comment by jrchamp** [comment]
I'm not seeing any problems, so here's one idea: The token used for an individual call only has a 40 second lifespan. Is it possible that your Moodle server's system time is out of sync?
