### ISSUE TITLE
Add a new release to update the installation docs?

### ISSUE THREAD

**Issue by renehamburger** [ucla/moodle-mod_zoom#75]
With the [docs of the latest version](https://moodle.org/plugins/pluginversion.php?id=20034) still pointing to the old API link and the [documentation link](https://github.com/ucla/moodle-mod_zoom/wiki/Adding-a-new-Zoom-meeting-Activity) underneath focussing on how to use the plugin once it's installed, it's tricky at the moment to figure out how to retrieve the API key. Would you be able to update this?

**Comment by rlorenzo** [comment]
Updated in https://github.com/ucla/moodle-mod_zoom/commit/aaffcc1a4ff8ec853b9ed4a7e7b1448870903d98
