### ISSUE TITLE
iCal contains a direct link to the meeting

### ISSUE THREAD

**Issue by nstefanski** [ucla/moodle-mod_zoom#76]
We discovered that if a student downloads the iCal event for a Zoom meeting, it contains the direct link to the meeting on Zoom rather than the meeting activity in Moodle. This is a problem because if the students access the meeting this way, they will not get credit for completing the activity in Moodle.

**Comment by rlorenzo** [comment]
Sounds reasonable. Merged in https://github.com/ucla/moodle-mod_zoom/pull/77
