### ISSUE TITLE
proxyurl regex forces a proxy to be used

### ISSUE THREAD

**Issue by danmarsden** [ucla/moodle-mod_zoom#80]
Issue #73 has a regex on the new global setting which prevents the proxyurl from being left as empty - which in turn prevents people from using this plugin if they do not have a proxy. The regex needs to be updated to allow an empty string or should be removed.

**Comment by rlorenzo** [comment]
@danmarsden Great catch!

@pefeigl Can you do that patch?

**Comment by pefeigl** [comment]
@danmarsden Sorry for the problems, it seems I didn't test this enough :-/ Should be fixed by #81.

**Comment by rlorenzo** [comment]
Fixed! Thanks for the report @danmarsden

**Comment by danmarsden** [comment]
thanks guys - crazy times! :-) - hope you're keeping safe!!
