### ISSUE TITLE
cron tasks shouldn't report "error" state when zoom not configured

### ISSUE THREAD

**Issue by danmarsden** [ucla/moodle-mod_zoom#82]
Ideally the cron tasks should be checking that the apikey is configured before sending to the mod_zoom_webservice class which triggers an exception when the api key is not configured - showing the cron task in a failed state. 

This is a problem for sites that monitor the cron tasks but moodle also does a bunch of re-try handling of a task when it returns an error state.

Ideally all the checks that trigger an exception here: (apikey/secret/) 
https://github.com/ucla/moodle-mod_zoom/blob/09373ca4947d6b83f3610dea0a26a1bd37cc9106/classes/webservice.php#L95

If missing - shouldn't generate a failed cron task - better to check if they are empty and just return at the top of each task.

eg here:
https://github.com/ucla/moodle-mod_zoom/blob/master/classes/task/get_meeting_reports.php#L70
if  apikey/secret are empty, just return and don't try to do anything else.

thanks!

**Comment by jrchamp** [comment]
Looks like the Moodle LTI tasks do something similar:
https://github.com/moodle/moodle/blob/73f8c56dfca5dd4028845f1fbbaac0a83e43caf9/enrol/lti/classes/task/sync_members.php#L79

**Comment by rlorenzo** [comment]
A fix for this would fix https://github.com/ucla/moodle-mod_zoom/issues/74

**Comment by rlorenzo** [comment]
Fixed in https://github.com/ucla/moodle-mod_zoom/commit/bb2c63f625c6d02d4cbbb50ddd005a67bba42049

**Comment by danmarsden** [comment]
thanks Rex!
