### ISSUE TITLE
Problem when adding new instances

### ISSUE THREAD

**Issue by cdipe** [ucla/moodle-mod_zoom#83]
When adding new instance, there's an error message and when clicking Continue one is sent to the Dashboard. No instance is setup.
When joining already setup meetings theres a meassage "Unable to join at this time", but clicking the link will start the meeting.
Using moodle 3.6+ and Zoom Meeting 2.2
Same problem in both QA and PROD environment.
This problem showed up recently, no changes from our side.
![problem message 2](https://user-images.githubusercontent.com/14754240/78125904-f9a7a100-7411-11ea-939a-f7aed3a9e979.png)
![problem message](https://user-images.githubusercontent.com/14754240/78125909-fad8ce00-7411-11ea-9237-606661171389.png)

**Comment by jrchamp** [comment]
The continue button in Moodle always sends you to the Dashboard/homepage. That's a quirk in how Moodle handles errors. The real problem here is the "You have reached the maximum per-second rate limit", which would probably be solved by #69 (better rate limit handling).

**Comment by ndunand** [comment]
What I generally do is  catch the exception and then call `print_error()` with the `$link` argument specified.

**Comment by rlorenzo** [comment]
Should be fixed in https://github.com/ucla/moodle-mod_zoom/commit/e88f877e9716f324c2ad437a015f6f3fa7217123
