### ISSUE TITLE
zoom_is_user_not_found_error has unstable logic

### ISSUE THREAD

**Issue by ndunand** [ucla/moodle-mod_zoom#84]
Code in https://github.com/ucla/moodle-mod_zoom/blob/master/locallib.php#L246 is generally fragile and will not work in localized Zoom versions. It contains hard-coded `strpos` calls referring to human-readable error messages that are prone to change.

In particular, we're using Zoom in French and the error message is not recognized as such, because it states (in French) : "`n’existe pas ou n’appartient pas à ce compte`".

I noticed that the `curl` HTTP response code is `404` and that the `$response->code` is `1001` which might be more portable to assess a non-existing user (to be verified though).

**Comment by jrchamp** [comment]
`zoom_is_meeting_gone_error` is also affected. Unfortunately, we can't use the `$code` member variable of `Exception`, because Moodle hard-codes that to `0`, so we might be able to add the `$response->code` to the string. It will still rely on strpos, which makes me sad, but it should still work for all languages.

**Comment by ndunand** [comment]
Thanks for your feedback. As some of this logic is done in `classes/webservice.php`, my initial approach was to add something like that (after the httpcode > 400 check) :

```
            if ($httpstatus == 404 && $response->code == 1001) {
                print_error('');
            }
```

After that I realised the logic resided in `locallib.php` and added the hard-coded string in french there, which fixes the issue, for now.

**Comment by rlorenzo** [comment]
@jrchamp @ndunand Our developer @kubilayagi has a patch to fix this bug reported. Please review if you have time. He is working on adding unit tests to ensure it works as expected.

**Comment by ndunand** [comment]
Thanks @kubilayagi @rlorenzo for your work in this.

I don't have time to test this now on our test system but the code looks good even though I still don't like the use of strpos much.

Can we be sure there won't be any unpredictable effects down the line? e.g. if we have one error code that is a substring of another one. Maybe the use of a regex enforcing word boundaries would be safer?

**Comment by jrchamp** [comment]
Thanks @rlorenzo @kubilayagi 

It'll be nice now that it doesn't rely on `strpos()`. As you probably saw, I had a number of questions about the unused httpstatus piece.

**Comment by rlorenzo** [comment]
@jrchamp @ndunand We cleaned up the code and looks ready to integration. We are going to do a few tests first.

Let us know if you have any additional feedback at https://github.com/ucla/moodle-mod_zoom/commit/e52d076489eedf6241c382fa330e00028be986a1#r41959040

**Comment by jrchamp** [comment]
I didn't see anything that needed to change. I had one suggestion, but it's more for readability/slight performance.

**Comment by rlorenzo** [comment]
Fixed in https://github.com/ucla/moodle-mod_zoom/commit/5f4a2fd15fbffe80a05a6e54948609fcb8a265b4
