### ISSUE TITLE
Call apis from the Zoom service

### ISSUE THREAD

**Issue by hoangph1990** [ucla/moodle-mod_zoom#85]
- Now , I installed plugin on the moodle and paied with the zoom but i make a meeting and member joined on the meeting, when i call api "https://api.zoom.us/v2/report/meetings/{meetingId}" , I get list about the  meeting , but  I go to the report page on the moodle I don't seem  the report table 
- I don't know where that  is't installed  exactly

- Can you help me ? Thank so much

**Comment by rlorenzo** [comment]
@hoangph1990 Make sure your Moodle cron is running. The meeting reports are generated once a day in the current version or 4 times a day on the newest master branch. See https://github.com/ucla/moodle-mod_zoom/blob/master/db/tasks.php#L38
