### ISSUE TITLE
Recent Zoom vulnerabilities 

### ISSUE THREAD

**Issue by n3ptuve** [ucla/moodle-mod_zoom#89]
Hi, 

There's been a lot in the news about Zoom security issues, especially around the issue of UNC path injections.

https://www.bleepingcomputer.com/news/security/zoom-lets-attackers-steal-windows-credentials-run-programs-via-unc-links/

Is this plugin impacted by the recent security issues that Zoom is experiencing?

Thanks,
C.J

**Comment by jrchamp** [comment]
No. The security "concerns" were all in the client/server/app. This plugin primarily just needed to be able to support things like joining meetings with a password, which should already work if people have the "embed password in link link" enabled.

**Comment by n3ptuve** [comment]
Thank you! 
C.J
