### ISSUE TITLE
DB upgrade error 1.3->1.4 on moodle 3.1

### ISSUE THREAD

**Issue by fluxcorenz** [ucla/moodle-mod_zoom#9]
I just attempted to perform an upgrade from 1.3 to 1.4 while upgrading moodle to 3.1 and received the following blocking error:

mod_zoom
Error writing to database

More information about this error

×Debug info: ERROR: column "type" is of type smallint but expression is of type boolean
LINE 1: UPDATE mdl_zoom SET type = (type = 3)
^
HINT: You will need to rewrite or cast the expression.
UPDATE mdl_zoom SET type = (type = 3)
[array (
)]
Error code: dmlwriteexception
×Stack trace:
line 477 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 712 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 152 of /mod/zoom/db/upgrade.php: call to pgsql_native_moodle_database->execute()
line 726 of /lib/upgradelib.php: call to xmldb_zoom_upgrade()
line 432 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

I went back to the v1.3 files on disk, completed the moodle 3.1 upgrade, and then tried to upgrade to zoom 1.4 again, and get the same error.

**Comment by rlorenzo** [comment]
We haven't updated to Moodle 3.1 yet. But are in the process. We are able to upgrade to Moodle 3.1 with the v1.4 version of the plugin, but haven't tried updating from 1.3 to 1.4 with Moodle 3.1 in-place already.

**Comment by fhung65** [comment]
Hi, I put in a change in a new branch (more-compatible-upgrade). Can you double check to see if this works on your server?

**Comment by rlorenzo** [comment]
@fluxcorenz We fixed this in https://github.com/ucla/moodle-mod_zoom/commit/75dade451e6fa65df0a444e89cc94802631b11d7 and will be releasing this patch in version 1.5. We tested this in Postgres and MySQL.
