### ISSUE TITLE
Error creating meeting

### ISSUE THREAD

**Issue by hmgp** [ucla/moodle-mod_zoom#90]
Hello, today I was trying to create Zoom meetings and I consistently get this error:

Debug info: ORA-01438: value larger than specified precision allowed for this column
INSERT INTO m_zoom (name,start_time,duration,recurring,webinar,password,option_host_video,option_participants_video,option_audio,option_jbh,alternative_hosts,meeting_id,host_id,grade,course,intro,introformat,start_url,join_url,created_at,timezone,timemodified) VALUES (:name,:start_time,:duration,:recurring,:webinar,:password,:option_host_video,:option_participants_video,:option_audio,:option_jbh,:alternative_hosts,:meeting_id,:host_id,:grade,:course,:intro,:introformat,:start_url,:join_url,:created_at,:timezone,:timemodified) RETURNING id INTO :oracle_id
[array (
'name' => 'By Plugin',
'start_time' => 1587034800,
'duration' => 3600,
'recurring' => 0,
'webinar' => '0',
'password' => '1234',
'option_host_video' => '1',
'option_participants_video' => 0,
'option_audio' => 'both',
'option_jbh' => 0,
'alternative_hosts' => 'xxx@ifb.pt',
'meeting_id' => 95590653806,
'host_id' => 'xxxnwx3Q0up8V96HQZn7g',
'grade' => 0,
'course' => 5904,
'intro' => '',
'introformat' => '1',
'start_url' => 'https://zoom.us/s/95590653806?zak=eyJ6bV9za20iOiJ6bV9vMm0iLCJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjbGllbnQiLCJ1aWQiOiJ1ZnpSbnd4M1EwdXA4Vjk2SFFabjdnIiwiaXNzIjoid2ViIiwic3R5IjoxMDAsIndjZCI6ImF3MSIsImNsdCI6MCwic3RrIjoiQ0IwTWJ0ZmhXLTZkSW1ZVUlMaU9XOUxwSE9rbGVsVUI4WVZLTU1rb0g1Zy5CZ1VnUWpRMFlqQnRNVEZqYmpjck5uaElRV00zZVRGRlRFRnBObG8yVWxCUFNYcEFZMlZpWm1Ka05UZ3lPREUyTlRaaU1qUmlNRGc0TW1VMllqUXdNVE5rWmpaa00yTTRNVFU1TW1NeE1qZ3pNbVF6T1RCaFptRTBZMlV3WlRRM1pUUTNOZ0FNTTBOQ1FYVnZhVmxUTTNNOUFBTmhkekUiLCJleHAiOjE1ODcwMzUzNzMsImlhdCI6MTU4NzAyODE3MywiYWlkIjoiU2FjLXNpOFRUU0NIMXRKeW9aSnFLdyIsImNpZCI6IiJ9.kNMPIN2qRZQBzwEjSQ5RFReXyAIkE3UHuPJ9T45-QQ8',
'join_url' => 'https://zoom.us/j/95590653806?pwd=dnJlZ2JuNExLYWROejQ3SHlGcTROZz09',
'created_at' => '2020-04-16T09:09:32Z',
'timezone' => 'Europe/London',
'timemodified' => 1587028173,
)]
Error code: dmlwriteexception 

From the Zoom side all the meetings are created, I think it's a problem in the table on the moodle side, Zoom must have changed something and is returning more than what the table field can have. 

I am trying to discover what is the problem. I will check back with my findings. It's in a Oracle database.

**Comment by hmgp** [comment]
Ok. Problem solved. Field meeting_id in table M_ZOOM was size 10, when Zoom is giving id with size 11. Changed table to size 14. Also table M_ZOOM_MEETING_DETAILS which had size 11 to size 14. Maybe that should be addressed in the next version. Thank you!

**Comment by jrchamp** [comment]
It looks like this problem only affects Oracle because the field "length" is taken literally in Moodle: https://github.com/moodle/moodle/blob/df0e58adb140f90712bcd3229ad936d3b4bc15d9/lib/ddl/oracle_sql_generator.php#L233

At this time, the new Zoom Meeting sizes are at 11, so the main table needs to change at a minimum:
https://github.com/ucla/moodle-mod_zoom/blob/cae951b0ca0171a3ee4f6e542e1895a68037965d/db/install.xml#L14

If, to be on the safe side, the length is increased beyond 11, it also makes sense to change the details table to match: https://github.com/ucla/moodle-mod_zoom/blob/cae951b0ca0171a3ee4f6e542e1895a68037965d/db/install.xml#L45

**Comment by hmgp** [comment]
To be on the safe side I upped to 14 in my Oracle database.
I just think maybe this should be on the next update.
Thank you.

**Comment by rlorenzo** [comment]
Yeah, Zoom increased their meeting ids. We would need to increase it to something like 15 (50% more) just to be future proof.

**Comment by rlorenzo** [comment]
Fixed in https://github.com/ucla/moodle-mod_zoom/commit/f764cf8514bd41da74ffde0951069ad5203876b7
