### ISSUE TITLE
wordpress and moodle zoom meeting error 404 when open the meeting

### ISSUE THREAD

**Issue by galiers** [ucla/moodle-mod_zoom#91]
Cheers

I have wordpress installed at the root of the site and moodle in a folder within the same root (intranet), moodle works without problems, and I can create meetings without problems too, but when I try to open the wordpress meeting it gives me a 404 error (page not found) with the Wordpress container and not moodle container.

wordpress: https://mydomain.com/ <- OK
moodle: https://mydomain.com/intranet <- OK
course: https://mydomain.com/intranet/course/view.php?id=60 <- OK
meeting: https://institutoprofesionalmr.org/intranet/mod/zoom/view.php?id=946 <-- ERROR 404

thanks

**Comment by rlorenzo** [comment]
@galiers I don't believe this is related to our plugin. You would seem to have problems with any other module. Unless you can point to what in our code would cause a problem for your setup we cannot help you.

**Comment by omniumlab** [comment]
I have the same error but my moodle is not in a wordpress subfolder, it is in a different subdomain.

Any solution or something to check from the configuration?

moodle: https://subdomain.mydomain.com <- OK
course: https://subdomain.mydomain.com/course/view.php?id=27 <- OK
meeting: https://subdomain.mydomain.com/mod/zoom/view.php?id=195 <-- ERROR 404
