### ISSUE TITLE
Error with Pro Account

### ISSUE THREAD

**Issue by Blacksheeprules** [ucla/moodle-mod_zoom#92]
I have set up the plugin with Moodle 3.8+ and put in the secret and API key. I get the error on adding the Zoom Activity in Moodle:
Unable to find your account on Zoom. If you are using Zoom for the first time, you must Zoom account by logging into Zoom <a href="https://zoom.us/j/2282300889" target="_blank" rel="noreferrer noopener">https://zoom.us/j/2282300889</a>. Once you've activated your Zoom account, reload this page and continue setting up your meeting. Else make sure your email on Zoom matches your email on this system.
Any help would be appreciated. Is it that I have a Pro account?

**Comment by rlorenzo** [comment]
@Blacksheeprules This integration requires a business or educational Zoom account to configure and setup.

**Comment by andrewmfsc** [comment]
I have a Business Zoom account and have the same problem, I can create Zoom meetings as an administrator, but Course Creators can't and get the same error message about having a zoom account

**Comment by mmn6d6d6e** [comment]
@rlorenzo does the business/education Zoom account required only for setting up API Key + secret or does it also required for creating activity on moodle?

**Comment by rlorenzo** [comment]
@mmn6d6d6e  Yes, teacher@university.com needs to be a licensed account under the moodle@university.com Zoom account
