### ISSUE TITLE
Only moodle admins can see meeting ID

### ISSUE THREAD

**Issue by cdipe** [ucla/moodle-mod_zoom#93]
![zoom 3](https://user-images.githubusercontent.com/14754240/79758944-5534c280-831e-11ea-9336-29581cac6d74.png)

![zoom 2](https://user-images.githubusercontent.com/14754240/79758554-d475c680-831d-11ea-9f45-16f564e6f1c8.png)
Using Moodle 3.6.6 and Zoom Meeting 2.2

**Comment by jrchamp** [comment]
It shows the join link to the host or alternative hosts:
https://github.com/ucla/moodle-mod_zoom/blob/a1d021530794b84465ece6b85353a545b504a56d/view.php#L61

https://github.com/ucla/moodle-mod_zoom/blob/a1d021530794b84465ece6b85353a545b504a56d/view.php#L176-L178

The Join Meeting URL is going to be the way that non-hosts join.

**Comment by rlorenzo** [comment]
@cdipe This was done on purpose. We want users to join via the join button so that we can log their participation and add in grades, if set-up.

**Comment by cdipe** [comment]
OK, thank you @rlorenzo !
