### ISSUE TITLE
Sessions report shows 0 participants for session UUIDs that begin with a slash

### ISSUE THREAD

**Issue by jonof** [ucla/moodle-mod_zoom#94]
For sessions with a UUID that begins with a forward-slash, no meeting participant information is retrieved from the Zoom API.

The Sessions report (mod/zoom/report.php) shows 0 participants even though a non-zero value in the underlying _zoom_meeting_details.participants_count_ database column exists.

For example, attempting to sync an affected meeting from the CLI:
```
php mod/zoom/cli/update_meeting_report.php '--meetinguuid=/KEH0....pI8w=='
Processiing detailsid: 5690 | meetindid: 68...3 | uuid: /KEH0....pI8w==
  Exception: Zoom webservice error: Meeting does not exist: KEH0....pI8w==..
```
Note the missing leading `/` in the error.

[Searching](https://devforum.zoom.us/search?q=uuid+slash+category%3A8) the Zoom developer forum [reveals that](https://devforum.zoom.us/t/wrong-symbols-in-uuid-v78xyi7tdmmtoeyjhfana/5986/2) `urlencode(urlencode($meetinguuid))` works around the problem, and indeed it does. Seems this has been an issue for years. 🙄

**Comment by jrchamp** [comment]
It looks like this may have been fixed 19 days ago in the master branch via 5733303
