### ISSUE TITLE
Retrieving Zoom user id from cache fails sometimes causing errors

### ISSUE THREAD

**Issue by yorickreum** [ucla/moodle-mod_zoom#96]
Today we encountered a lot of errors of the type:
`[Mon Apr 27 08:35:56.797222 2020] [php7:notice] [pid 15565] [client XX.XX.XXX.XX:59227] Default exception handler: Coding error detected, it must be fixed by a programmer:  Failed to unserialise data from file. Either failed to read, or failed to write. Debug: \nError code: codingerror\n* line 470 of /cache/stores/file/lib.php: coding_exception thrown\n* line 373 of /cache/stores/file/lib.php: call to cachestore_file->prep_data_after_read()\n* line 1816 of /cache/classes/loaders.php: call to cachestore_file->get()\n* line 207 of /mod/zoom/locallib.php: call to cache_session->get()\n* line 55 of /mod/zoom/view.php: call to zoom_get_user_id()\n, referer: https://xxx.de/moodle/course/view.php?id=xxxxx
`
`There was a file locked by cache store system.`

These errors are visible to our users and seemed to have caused a lot of trouble. Therefore we have chosen to disable the user-id caching as a workaround, therefore we edited `mod/zoom/locallib.php` as follows:

```php
function zoom_get_user_id($required = true) {
    global $USER;

//    $cache = cache::make('mod_zoom', 'zoomid');
//    if (!($zoomuserid = $cache->get($USER->id))) {
        $zoomuserid = false;
        $service = new mod_zoom_webservice();
        try {
            $zoomuser = $service->get_user($USER->email);
            if ($zoomuser !== false) {
                $zoomuserid = $zoomuser->id;
            }
        } catch (moodle_exception $error) {
            if ($required) {
                throw $error;
            } else {
                $zoomuserid = $zoomuser->id;
            }
        }
//        $cache->set($USER->id, $zoomuserid);
//    }

    return $zoomuserid;
}
```

This clearly is only a workaround until further investigation, we just wanted to share this with you just in case anyone else stumbles into this issue and needs a quick fix.

**Comment by rlorenzo** [comment]
@yorickreum See this forum thread: https://moodle.org/mod/forum/discuss.php?d=240739
Something went wrong with your caches and need to be purged. Purging your cache should fix it.

**Comment by yorickreum** [comment]
@rlorenzo We already read this thread and tried both solutions mentioned there (running `php admin/cli/purge_caches.php` and removing all files in `/moodledata/cache` directly). Both only prevented the error from occurring for only a couple of minutes (we tried it multiple times…). So we think that there is a deeper-rooted source of error. Sorry, I should have mentioned this earlier!
