### ISSUE TITLE
Activity Completation Request

### ISSUE THREAD

**Issue by ExaMuff** [ucla/moodle-mod_zoom#97]
Hi, is possible to add another Activity Completation option like User stay in Webinar for XX% of total time or something like this?
This could be useful for set completed for student who stay in webinar and not just click on link

Thanks

**Comment by ExaMuff** [comment]
hey, any update?

**Comment by jrchamp** [comment]
It's a bit less possible. It won't work reliably unless the user has their own Zoom account using the same email address as their Moodle user account and is logged in.

**Comment by rlorenzo** [comment]
@ExaMuff Support for this is coming in https://github.com/ucla/moodle-mod_zoom/pull/117
