### ISSUE TITLE
Alternate Hosts - Being Saved with Semicolons

### ISSUE THREAD

**Issue by jrchamp** [ucla/moodle-mod_zoom#99]
I created a Zoom meeting activity with two alternative host emails separated by only a comma. In the database and on the view activity page, it is showing the lists of emails as semi-colon separated. I believe this is a bug in the current version of the Zoom API, so I posted it on the dev forum: https://devforum.zoom.us/t/undocumented-api-change-alternative-hosts-separated-by-semicolon/16683

However, there are probably a large number of meetings that have been created with incorrect alterative_hosts values.

It would be good to either fix them or accept either separator. Here are the two places where the value is parsed by this plugin:

https://github.com/ucla/moodle-mod_zoom/blob/4bf777573ee62ef8c5999ab7f49d52edc276380f/view.php#L58

https://github.com/ucla/moodle-mod_zoom/blob/4bf777573ee62ef8c5999ab7f49d52edc276380f/mod_form.php#L243

**Comment by jrchamp** [comment]
For now, my stopgap solution was to swap semicolons to commas in the two places where the value is parsed:
```diff
-$alternativehosts = explode(',', $zoom->alternative_hosts);
+$alternativehosts = explode(',', str_replace(';', ',', $zoom->alternative_hosts));
```
```diff
-$alternativehosts = explode(',', $data['alternative_hosts']);
+$alternativehosts = explode(',', str_replace(';', ',', $data['alternative_hosts']));
```

**Comment by rlorenzo** [comment]
@jrchamp Wow.. good catch. I see semicolons in our database as well. Fixed.
